#=====  ANSIBLE   =============================================================
#          NAME:  group_vars/all
#   DESCRIPTION:  Common variables that apply to this play
#==============================================================================
---
