#======  ANSIBLE  ============================================================
#          NAME:  tasks/main.yml
#   DESCRIPTION:  Primary entry point for this play
#==============================================================================
---
- name: Install bind and bind-utils
  become: true
  become_method: sudo

  dnf:
    name:
      - bind
      - bind-utils
    state: latest
