#=====  ANSIBLE   =============================================================
#          NAME:  site.yml
#   DESCRIPTION:  Entry point for all plays within this playbook
#==============================================================================
---
- hosts: ldap
  gather_facts: true
  vars:
    is_ldap: true
    is_maildrop: false
    is_pop: false
  roles:
    - build-zimbra
    - jira-tasks
  tags:
    - build-ldap

- hosts: maildrop
  gather_facts: true
  vars:
    is_ldap: false
    is_maildrop: true
    is_pop: false
  roles:
    - build-zimbra
    - jira-tasks
  tags:
    - build-maildrop

- hosts: ecmgr
  gather_facts: true
  roles:
    - build-ecelerity
  tags:
    - build-ecmgr

- hosts: smtp
  gather_facts: true
  roles:
    - build-ecelerity
    - jira-tasks
  tags:
    - build-smtp

- hosts: mx
  gather_facts: true
  roles:
    - build-ecelerity
    - jira-tasks
  tags:
    - build-mx

- hosts: nginx
  gather_facts: true
  vars:
    is_ldap: false
    is_maildrop: false
    is_pop: true
  roles:
    - build-nginx
    - jira-tasks
  tags:
    - build-nginx
