#=====  ANSIBLE   =============================================================
#          NAME:  site.yml
#   DESCRIPTION:  Entry point for all plays within this playbook
#==============================================================================
---
- hosts: ldap
  gather_facts: true
  roles:
    - build-zimbra
  tags:
    - build-ldap

- hosts: maildrop
  gather_facts: true
  roles:
    - build-zimbra
  tags:
    - build-maildrop

- hosts: ecelerity
  gather_facts: true
  roles:
    - build-ecelerity
  tags:
    - build-ecmgr

- hosts: ecelerity
  gather_facts: true
  roles:
    - build-ecelerity
  tags:
    - build-smtp

- hosts: ecelerity
  gather_facts: true
  roles:
    - build-ecelerity
  tags:
    - build-mx

- hosts: nginx
  gather_facts: true
  roles:
    - build-nginx
  tags:
    - build-nginx
