#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/ldap/replica.yml
#   DESCRIPTION:  Enable LDAP replicas
#==============================================================================
---
##
## Set up replica if this is an ldap master
##
- name: (POSTINSTALL) Run zmldapenablereplica if this is an LDAP master
  command: /opt/zimbra/libexec/zmldapenablereplica
  become: yes
  become_user: zimbra
  become_method: sudo

- name: Stop LDAP services
  command: "{{ install_dir }}/bin/ldap stop"

- name: Pause for 30 seconds to allow completion
  pause:
    prompt="Pause for 30 seconds to allow LDAP shutdown"
    seconds=30

- name: Start LDAP after change
  command: "{{ install_dir }}/bin/ldap start"
