#=====  ANSIBLE   =============================================================
#          NAME:  main.yml
#   DESCRIPTION:  Primary entry point for play
#==============================================================================
---
- name: Perform system-wide update
  yum:
    name=*
    state=latest
    update_cache=yes
  notify:
    - sync puppet

- meta:
    flush_handlers
