#=====  ANSIBLE   =============================================================
#          NAME:  main.yml
#   DESCRIPTION:  Primary entry point for play
#==============================================================================
---
- name: Perform system-wide update
  yum:
    name=*
    state=latest
    update_cache=yes

- name: Sync with puppet master
  command: /usr/bin/puppet agent -t
  ignore_errors: yes
