#=====  ANSIBLE   =============================================================
#          NAME:  build-ecelerity/vars/main.yml
#   DESCRIPTION:  Variables that apply to Mail Transport Agent servers
#==============================================================================
---
##
## accounting
##
group_id: 454
group_name: ecuser
addl_groups:
home_dir: /opt/home/ecuser
user_name: ecuser
user_shell: /bin/bash
user_uid: 454
