#=====  ANSIBLE   =============================================================
#          NAME:  build-ecelerity/vars/main.yml
#   DESCRIPTION:  Variables that apply to Mail Transport Agent servers
#==============================================================================
---
##
## accounting
##
group_id: 454
group_name: ecuser
addl_groups: 
home_dir: /opt/home/ecuser
user_name: ecuser
user_shell: /bin/bash
user_uid: 454

##
## disks
##
mountpoints:
  - name: /opt

##
## template updates
##
install_dir: /opt/msys/ecelerity
manager_hostname: "ecmgr01.{{ client_name }}.{{ datacenter }}.synacor.com"
manager_ipaddr: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
cluster_group: ec_cluster
control_group: ec_cosole

maildrops:
 - list
 - of
 - drops

##
## subversion!
##
inbound.svn.host: "https://ecmgr01.{{ client_name }}.{{ datacenter }}.synacor.com:2027/config/inbound/boot"
outbound.svn.host: "https://ecmgr01.{{ client_name }}.{{ datacenter }}.synacor.com:2027/config/outbound/boot"
