#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/main.yml
#   DESCRIPTION:  Entry point for the Zimbra build play
#==============================================================================
---
##
## Check for appropriate disks
##
- name: (PREINSTALL) Ensure mountpoints exist
  stat:
    path="{{ item }}"
  register: mount_exists
  with_items: "{{ mountpoints|default([]) }}"

- name: (PREINSTALL) Create disks and filesystems
  include: disks/create-disks.yml
  when: not mount_exists

##
## Create user group/account
##
- name: (PREINSTALL) Create user group
  group:
    gid="{{ group_id }}"
    name="{{ group_name }}"
    system=yes

- name: (PREINSTALL) Create user account
  user:
    group="{{ group_name }}"
    groups="{{ addl_groups }}"
    home="{{ home_dir }}"
    name="{{ user_name }}"
    shell="{{ user_shell }}"
    state=present
    uid="{{ user_uid }}"

##
## Install system packages, if any
- name: Install necessary system packages
  yum:
    name="{{ item }}"
    state=present
  with_items: "{{ system_packages|default([]) }}"
