#=====  ANSIBLE   =============================================================
#          NAME:  build-nginx/tasks/run-installation.yml
#   DESCRIPTION:  Perform software installation
#==============================================================================
---
##
## Run installation steps
##
- name: Install nginx
  yum:
    name: "nginx-{{ pkg_version }}.{{ hostvars[inventory_hostname]['ansible_architecture'] }}"
    state: present

