#=====  ANSIBLE   =============================================================
#          NAME:  build-nginx/tasks/run-postinstall.yml
#   DESCRIPTION:  Configure Zimbra maildrop post-installation
#==============================================================================
---
##
## Generate 2048 bit DH key
##
- name: (POSTINSTALL) Stop nginx (if running)
  service:
    name=nginx
    state=stopped
  ignore_errors: yes

- name: (POSTINSTALL) Stop Apache (if running)
  service:
    name=httpd
    state=stopped
  ignore_errors: yes

- name: (POSTINSTALL) Stop Zimbra (if running)
  service:
    name=zimbra
    state=stopped
  ignore_errors: yes

- name: (POSTINSTALL) Create nginx SSL directory
  file:
    path=/etc/nginx/ssl
    state=directory

- name: (POSTINSTALL) Generate 2048 bit DH key for nginx (logjam)
  command: "/usr/bin/openssl dhparam -out {{ dhparam_output }} {{ dhparam_keysize }}"

##
## Update nginx config
##
- name: (POSTINSTALL) Apply nginx configuration updates
  template:
    src=nginx.j2
    dest="{{ nginx_conf }}"
    owner="{{ file_owner }}"
    group="{{ group_owner }}"
    mode=0644

- name: (POSTINSTALL) Apply auth.php
  template:
    src=auth.j2
    dest=/var/www/html
    owner="{{ file_owner }}"
    group="{{ group_owner }}"
    mode=0600

- name: (POSTINSTALL) Fix onboard Apache
  replace:
    backup=yes
    dest=/etc/httpd/conf/httpd.conf
    regexp='^Listen 80'
    replace='Listen 127.0.0.1:81'
    validate="/usr/sbin/apachectl -f %s -t"

##
## Apply proxy config
##
- name: Apply Zimbra proxy configuration
  command: "{{ install_dir }}/libexec/zmproxyconfig -w -e -u -a 0:80:0:443 -x both -H {{ hostvars[inventory_hostname]['ansible_fqdn'] }}"
  become: yes
  become_user: zimbra
  become_method: sudo

##
## Create a self-signed certificate if necessary
##
- name: (POSTINSTALL) Creating self-signed server SSL cert
  command:
    openssl req -new
      -x509
      -nodes
      -extensions v3_ca
      -days {{ item.days|default(30) }}
      -subj "/C={{ item.country|default('US') }}/ST={{ item.state|default('New York') }}/L={{ item.city|default('Buffalo') }}/O={{ item.organization|default('Synacor, Inc') }}/OU={{ item.unit|default('Email Operations') }}/CN={{ item.name }}/emailAddress={{ item.email|default('emailops@synacor.com') }}"
      -keyout {{ openssl_keys_path }}/{{ item.name }}.key
      -out {{ openssl_certs_path }}/{{ item.name }}.crt
  args:
    creates: "{{ openssl_certs_path }}/{{ item.name }}.crt"
  with_items: openssl_self_signed
  when: self_signed_enabled|bool

#- name: (POSTINSTALL) Create a self-signed certificate if necessary
#  command: "openssl req -new -nodes -x509 -subj {{ self_signed_cn }} -days 90 -keyout /etc/nginx/ssl/mail.{{ domain }}.key -out /etc/nginx/ssl/mail.{{ domain }}.crt -extensions v3_ca" creates="/etc/nginx/ssl/mail.{{ domain }}.crt"
#  when: self_signed_enabled|bool

##
## Start everything back up
##

- name: (POSTINSTALL) Restart nginx
  service:
    name=nginx
    state=started
  ignore_errors: yes

- name: (POSTINSTALL) Restart Apache
  service:
    name=httpd
    state=started
  ignore_errors: yes

- name: (POSTINSTALL) Restart Zimbra
  service:
    name=zimbra
    state=started
  ignore_errors: yes

##
## POSTINSTALL COMPLETE
##
