#=====  ANSIBLE   =============================================================
#          NAME:  build-nginx/tasks/run-installation.yml
#   DESCRIPTION:  Perform software installation
#==============================================================================
---
##
## Run installation steps
##
- name: (INSTALL) Install selected packages (NGINX)
  yum:
    name: "{{ item.name }}-{{ item.version }}"
    state: present
  with_items: "{{ nginx_packages|default([]) }}"

- name: Notify puppet
  command: puppet agent -t
  ignore_errors: yes

##
## INSTALLATION COMPLETE
##
