#=====  ANSIBLE   =============================================================
#          NAME:  build-ecelerity/default/main.yml
#   DESCRIPTION:  Common variables that apply to this play
#          NOTE:  Variables housed in this document are the *least* preferred
#==============================================================================
---
