#=====  ANSIBLE   =============================================================
#          NAME:  build-ecelerity/default/main.yml
#   DESCRIPTION:  Common variables that apply to this play
#          NOTE:  Variables housed in this document are the *least* preferred
#==============================================================================
---
#==============================================================================
# BEGIN ${PLAYBOOK_DIR}/ROLES/${ROLE_NAME}/VARS/MAIN.YML
# Highest preference, wins against all except command line
#==============================================================================

#==============================================================================
# END ${PLAYBOOK_DIR}/ROLES/${ROLE_NAME}/VARS/MAIN.YML
#==============================================================================

#==============================================================================
# BEGIN ${PLAYBOOK_DIR}/HOST_VARS/${HOSTNAME}
# Second preference, wins against all except above
#==============================================================================

#==============================================================================
# END ${PLAYBOOK_DIR}/HOST_VARS/${HOSTNAME}
#==============================================================================

#==============================================================================
# BEGIN ${PLAYBOOK_DIR}/GROUP_VARS/${GROUP}/*
# Third preference, wins against all except above
#==============================================================================
##
## accounting
##
group_id: 454
group_name: ecuser
addl_groups: 
home_dir: /opt/home/ecuser
user_name: ecuser
user_shell: /bin/bash
user_uid: 454

##
## disks
##
mountpoints:
  - name: /opt

##
## template updates
##
install_dir: /opt/msys/ecelerity
manager_hostname: "ecmgr01.{{ client_name }}.{{ datacenter }}.synacor.com"
manager_ipaddr: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
cluster_group: ec_cluster
control_group: ec_console

maildrops:
 - list
 - of
 - drops

##
## subversion!
##
inbound.svn.host: "https://ecmgr01.{{ client_name }}.{{ datacenter }}.synacor.com:2027/config/inbound/boot"
outbound.svn.host: "https://ecmgr01.{{ client_name }}.{{ datacenter }}.synacor.com:2027/config/outbound/boot"

##
## datasource config
##
datasources:
  - name: ldap_bind_auth
    uri: "ldap://{{ ldap_host }}:389/????"
    cache-size: 300000
    cache-life: 900
  - name: ldap_auth
    uri: "ldap://{{ ldap_host }}:389/????bindname=uid=zimbra%2ccn=admins%2ccn=zimbra,x-bindpw={{ ldap_admin_pass }}"
    cache-size: 300000
    cache-life: 360
  - name: user_check
    uri: "ldap://{{ ldap_host }}:389/????bindname=uid=zimbra%2ccn=admins%2ccn=zimbra,x-bindpw={{ ldap_admin_pass }}"
    cache-size: 300000
    cache-life: 360
  - name: domain_check
    uri: "ldap://{{ ldap_host }}:389/????bindname=uid=zimbra%2ccn=admins%2ccn=zimbra,x-bindpw={{ ldap_admin_pass }}"
    cache-size: 300000
    cache-life: 360
  - name: md_check
    uri: "ldap://{{ ldap_host }}:389/????bindname=uid=zimbra%2ccn=admins%2ccn=zimbra,x-bindpw={{ ldap_admin_pass }}"
    cache-size: 300000
    cache-life: 360
  - name: catch_all_check
    uri: "ldap://{{ ldap_host }}:389/????bindname=uid=zimbra%2ccn=admins%2ccn=zimbra,x-bindpw={{ ldap_admin_pass }}"
    cache-size: 300000
    cache-life: 360
  - name: bind_check
    uri: "ldap://{{ ldap_host }}:389/????bindname=uid=zimbra%2ccn=admins%2ccn=zimbra,x-bindpw={{ ldap_admin_pass }}"
    cache-size: 300000
    cache-life: 360
  - name: cidr
    uri: "sqlite:{{ install_dir }}/etc/conf/global/ec_lists.db"
    cache-size: 100000
    cache-life: 1800
  - name: global
    uri: "sqlite:{{ install_dir }}/etc/conf/global/ec_lists.db"
    cache-size: 100000
    cache-life: 1800
  - name: internal
    uri: "sqlite:{{ install_dir }}/etc/conf/global/ec_lists.db"
    cache-size: 100000
    cache-life: 1800
  - name: conn
    uri: "sqlite:{{ install_dir }}/etc/conf/global/ec_lists.db"
    cache-size: 100000
    cache-life: 1800
  - name: wlbl
    uri: "sqlite:{{ install_dir }}/etc/conf/global/synacor.db"
    cache-size: 10000
    cache-life: 360
  - name: rate_limit
    uri: "sqlite:{{ install_dir }}/etc/conf/global/synacor.db"
    cache-size: 100000
    cache-life: 60
  - name: fail_check
    uri: "sqlite:{{ install_dir }}/etc/conf/global/synacor.db"
    cache-size: 100000
    cache-life: 60
  - name: relays
    uri: "sqlite:{{ install_dir }}/etc/conf/global/synacor.db"
    cache-size: 10000
    cache-life: 60
  - name: biz
    uri: "sqlite:{{ install_dir }}/etc/conf/global/synacor.db"
    cache-size: 10000
    cache-life: 60
  - name: outbind
    uri: "sqlite:{{ install_dir }}/etc/conf/global/synacor.db"
    cache-size: 10
    cache-life: 60

inbound_hosts:
  - name: "mx01.{{ client_name }}.{{ datacenter }}.synacor.com"
    address: <ipaddr>
  - name: "mx02.{{ client_name }}.{{ datacenter }}.synacor.com"
    address: <ipaddr>

outbound_hosts:
  - name: "{{ hostvars[inventory_hostname]['ansible_fqdn'] }}"
    address: <ipaddr>
  - name: "smtp01.{{ client_name }}.{{ datacenter }}.synacor.com"
    address: <ipaddr>
#==============================================================================
# END ${PLAYBOOK_DIR}/GROUP_VARS/${GROUP}/*
#==============================================================================

#==============================================================================
# BEGIN ${PLAYBOOK_DIR}/GROUP_VARS/ALL
# Fourth preference, wins against all except above
#==============================================================================

#==============================================================================
# END ${PLAYBOOK_DIR}/GROUP_VARS/ALL
#==============================================================================
