#=====  ANSIBLE   =============================================================
#          NAME:  handlers/main.yml
#   DESCRIPTION:  Notification handler for completed plays
#==============================================================================
# send a message, specifying the host and port
- name: Notify emailops channel (jabber)
  jabber:
    user=khuntly@chat.corp.synacor.com
    host=chat.corp.synacor.com
    port=5222
    password=secret
    to=email@conference.chat.corp.synacor.com
    msg="test message"

- name: ldap-build-complete
  jabber:
    user=khuntly@chat.corp.synacor.com
    host=chat.corp.synacor.com
    port=5222
    password=secret
    to=email@conference.chat.corp.synacor.com
    msg="test message"

- name: maildrop-build-complete
  jabber:
    user=khuntly@chat.corp.synacor.com
    host=chat.corp.synacor.com
    port=5222
    password=secret
    to=email@conference.chat.corp.synacor.com
    msg="test message"

- name: smtp-build-complete
  jabber:
    user=khuntly@chat.corp.synacor.com
    host=chat.corp.synacor.com
    port=5222
    password=secret
    to=email@conference.chat.corp.synacor.com
    msg="test message"

- name: mx-build-complete
  jabber:
    user=khuntly@chat.corp.synacor.com
    host=chat.corp.synacor.com
    port=5222
    password=secret
    to=email@conference.chat.corp.synacor.com
    msg="test message"

- name: nginx-build-complete
  jabber:
    user=khuntly@chat.corp.synacor.com
    host=chat.corp.synacor.com
    port=5222
    password=secret
    to=email@conference.chat.corp.synacor.com
    msg="test message"
