#======  ANSIBLE  ============================================================
#          NAME:  site.yml
#   DESCRIPTION:  Entry point for playbook
#==============================================================================
---
- name: Distribute Profile
  hosts: all

  tasks:
   - name: Add user
     ansible.builtin.user:
       name: dnsadm
     become: yes
