#=====  ANSIBLE   =============================================================
#          NAME:  build-nginx/default/main.yml
#   DESCRIPTION:  Common variables that apply to this play
#          NOTE:  Variables housed in this document are the *least* preferred
#==============================================================================
---
#==============================================================================
# BEGIN ${PLAYBOOK_DIR}/ROLES/${ROLE_NAME}/VARS/MAIN.YML
# Highest preference, wins against all except command line
#==============================================================================
self_signed_enabled: TRUE
self_signed_cn: "/C=US/ST=New York/L=Buffalo/O=Synacor, Inc/CN=mail.{{ domain }}"
#==============================================================================
# END ${PLAYBOOK_DIR}/ROLES/${ROLE_NAME}/VARS/MAIN.YML
#==============================================================================

#==============================================================================
# BEGIN ${PLAYBOOK_DIR}/HOST_VARS/${HOSTNAME}
# Second preference, wins against all except above
#==============================================================================

#==============================================================================
# END ${PLAYBOOK_DIR}/HOST_VARS/${HOSTNAME}
#==============================================================================

#==============================================================================
# BEGIN ${PLAYBOOK_DIR}/GROUP_VARS/NGINX/*
# Third preference, wins against all except above
#==============================================================================
##
## disks
##
mountpoints:
  - name: /opt

##
## accounting
##
group_id: 454
group_name: nginx
addl_groups: 
home_dir: /var/lib/nginx
user_name: nginx
user_shell: /sbin/nologin
user_uid: 454

##
## install data
##
build_type: POP/IMAP Proxy
nginx_conf: /etc/nginx/nginx.conf
nginx_version: 1.4.7-3
dhparam_keysize: 2048
dhparam_output: /etc/nginx/ssl/dhparams-nginx.pem
install_packages: zimbra-core zimbra-memcached zimbra-proxy
is_ldap: FALSE
is_maildrop: FALSE
is_pop: TRUE
is_mta: FALSE
create_default_accounts: FALSE
create_maildrop_accounts: FALSE
setup_stores: FALSE
use_scality: FALSE
use_reverse_proxy: TRUE
activate_license: FALSE
do_create_domain: no
ldap_url: "ldap://ldap01.{{ client_name }}.{{ datacenter }}.synacor.com:389/"

##
## yum installs
##
packages:
  - name: nginx
    version: "{{ nginx_version }}.{{ hostvars[inventory_hostname]['ansible_architecture'] }}"
  - name: zimbra-core
    version: "{{ pkg_version }}.{{ hostvars[inventory_hostname]['ansible_architecture'] }}"
  - name: zimbra-proxy
    version: "{{ pkg_version }}.{{ hostvars[inventory_hostname]['ansible_architecture'] }}"
  - name: zimbra-memcached
    version: "{{ pkg_version }}.{{ hostvars[inventory_hostname]['ansible_architecture'] }}"
  - name: scapi-consumers
    version: 2.5.2-102.noarch
  - name: scapi-core
    version: 2.5.2-102.noarch
  - name: scapi-dao-zimbra8.0.7.synacor
    version: 2.5.2-102.noarch

##
## configuration
##
hosts:
  - domain: default.com
    port.pop3: 110
    port.pop3s: 995
    port.imap: 143
    port.imaps: 993

cos_id: b1d6a2cb-d4bb-4479-a613-c45736d7986c
blacklist_file: /opt/zimbra/conf/nginx/blacklisted_ips.txt

##
## JIRA
##
jira_summary: "Request for Proxy VIP: {{ client_name }}/{{ datacenter }}"
jira_description: "Please create [smtp|pop|webmail].{{ client_name }}.{{ datacenter }} .caspersbox.comVIP with targets {{ address }}"
#==============================================================================
# END ${PLAYBOOK_DIR}/GROUP_VARS/NGINX/*
#==============================================================================

#==============================================================================
# BEGIN ${PLAYBOOK_DIR}/GROUP_VARS/ALL
# Fourth preference, wins against all except above
#==============================================================================

#==============================================================================
# END ${PLAYBOOK_DIR}/GROUP_VARS/ALL
#==============================================================================
