#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/create-disks.yml
#   DESCRIPTION:  Entry point for the Zimbra build play
#==============================================================================
---
- name: (COMMON) Create Zimbra volume group
  lvg:
    pvs=/dev/sdb, /dev/sdc, /dev/sdd
    state=present
    vg=vg_zimbra

- name: (COMMON) Creating logical volumes (lv_zimbra)
  lvol:
    lv=lv_zimbra
    size=12799
    state=present
    vg=vg_zimbra

- name: (COMMON) Creating logical volumes (lv_index)
  lvol:
    lv=lv_index
    size=76799
    state=present
    vg=vg_zimbra

- name: (COMMON) Creating logical volumes (lv_db)
  lvol:
    lv=lv_db
    size=25599
    state=present
    vg=vg_zimbra

- name: (COMMON) Creating filesystem on vg_zimbra/lv_zimbra
  filesystem:
    fstype=ext4
    dev=/dev/vg_zimbra/lv_zimbra

- name: (COMMON) Creating filesystem on vg_zimbra/lv_db
  filesystem:
    fstype=ext4
    dev=/dev/vg_zimbra/lv_db

- name: (COMMON) Creating filesystem on vg_zimbra/lv_index
  filesystem:
    fstype=ext4
    dev=/dev/vg_zimbra/lv_index

- name: (COMMON) Mounting filesystem /opt/zimbra
  mount:
    fstype=ext4
    name=/opt/zimbra
    src=/dev/vg_zimbra/lv_zimbra
    state=mounted

- name: (COMMON) Mounting filesystem /opt/zimbra/db
  mount:
    fstype=ext4
    name=/opt/zimbra/db
    src=/dev/vg_zimbra/lv_db
    state=mounted

- name: (COMMON) Mounting filesystem /opt/zimbra/index
  mount:
    fstype=ext4
    name=/opt/zimbra/index
    src=/dev/vg_zimbra/lv_index
    state=mounted

