#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/vars/main.yml
#   DESCRIPTION:  Common variables that apply to this play
#==============================================================================
---
##
## accounting
##
group_id: 454
group_name: zimbra
addl_groups: adm,tty,postfix
home_dir: /opt/home/zimbra
user_name: zimbra
user_shell: /bin/bash
user_uid: 454

##
## disks
##
mountpoints:
  - name: /opt/zimbra
  - name: /opt/zimbra/index
  - name: /opt/zimbra/db

##
## install data
##
install_dir: /opt/zimbra
run_zmfixperms_extended: TRUE
pkg_version: 8.0.7_GA_6021.RHEL6_64-20140408123937
build_ecmgr: FALSE
disable_fsck: FALSE
mailboxd_java_options: "-XX:+UseConcMarkSweepGC -XX:PermSize=128m -XX:MaxPermSize=350m -XX:SoftRefLRUPolicyMSPerMB=1 -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCApplicationStoppedTime -XX:-OmitStackTraceInFastThrow -XX:+UseParNewGC -XX:NewRatio=2 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/zimbra/store/log -XX:ErrorFile=/opt/zimbra/log/hs_err_pid%p.log"

##
## version info
##
zimbra_version: 807
zimbra_major_version: 8

##
## LDAP
##
ldap_master_url: "ldap://ldap01.{{ client_name }}.{{ datacenter }}.synacor.com:389/ ldap://ldap02.{{ client_name }}.{{ datacenter }}.synacor.com:389/ ldap://ldap03.{{ client_name }}.{{ datacenter }}.synacor.com:389/ ldap://ldap04.{{ client_name }}.{{ datacenter }}.synacor.com:389/"
admin_address: "admin@{{ client_name }}.{{ datacenter }}.synacor.com"
is_multimaster: TRUE

##
## client-specific attributes
##
client_domains:
 - kevin.com
cos_list:
 - mycos

##
## smtp
##
smtp_host: "mailrelay.{{ client_name }}.{{ datacenter }}.synacor.com"
smtp_source:
smtp_dest:
email_dest: khuntly@synacor.com

##
## custom skins/zimlets as necessary
##
customizations:
  - zimlet1
  - skin1
