#======  ANSIBLE  ============================================================
#          NAME:  tasks/main.yml
#   DESCRIPTION:  Primary entry point for this play
#=============================================================================
---
- name: Remove dotfiles pull
  ansible.builtin.file:
    path: "~/.dotfiles"
    state: absent

- name: Extract dotfiles zip
  ansible.builtin.unarchive:
    src: /var/tmp/dotfiles.zip
    dest: "~/"
  notify:
    - executeInstallation
