#======  ANSIBLE  ============================================================
#          NAME:  tasks/main.yml
#   DESCRIPTION:  Primary entry point for this play
#==============================================================================
---
- name: Set up SSH
  include: ssh.yml

- name: Include sync
  include: sync.yml

- name: Set up configuration files for Java apps
  include: update-config.yml
