#======  ANSIBLE  ============================================================
#          NAME:  tasks/ssh.yml
#   DESCRIPTION:  Add authorized_keys to target hosts
#==============================================================================
---
##
## Send public keys
##
- name: Set up authorized_keys
  authorized_key:
    key="{{ item }}"
    state=present
    user=khuntly
    exclusive=yes
    key_options="{{ key_options }}"
  with_file:
    - "{{ ssh_keyfile }}"

- name: Remove any extra files found
  file:
    path="/home/khuntly/.ssh/{{ item }}"
    state=absent
  with_items:
    - id_rsa
    - id_rsa.pub
    - id_dsa
    - id_dsa.pub
    - id_ecdsa
    - id_ecdsa.pub
    - known_hosts
