#======  ANSIBLE  ============================================================
#          NAME:  tasks/ssh.yml
#   DESCRIPTION:  Add authorized_keys to target hosts
#==============================================================================
---
##
## Send public keys
##
- name: Set up authorized_keys (with key options)
  authorized_key:
    key="{{ item }}"
    key_options="{{ key_options }}"
    state=present
    user=khuntly
  with_file:
    - "/home/khuntly/.ssh/id_rsa.pub"
  when: add_key_options|bool

- name: Set up authorized_keys (without key options)
  authorized_key:
    key="{{ item }}"
    state=present
    user=khuntly
  with_file:
    - "/home/khuntly/.ssh/id_rsa.pub"
  when: not add_key_options|bool

- name: update ssh config
  template:
    src=ssh/config.j2
    dest="{{ remote_home }}/.ssh/config"
    owner="{{ remote_user }}"
    group="{{ remote_group }}"
    mode=0644
