---
- name: Synchronize profile across hosts
  synchronize:
    src="{{ ansible_env.HOME }}/dotfiles"
    dest="{{ remote_home }}"
    archive=yes
    checksum=yes
    compress=no
    mode=push
    perms=yes
    recursive=yes
    rsync_timeout=0
    rsync_opts="-avr --exclude-from={{ ansible_env.HOME }}/.etc/excludes --no-motd --stats --progress"
  notify:
    - install

- name: Copy/create files
  copy:
    src="{{ ansible_env.HOME }}/.etc/sudo"
    dest="{{ remote_home }}/.etc/sudo"
    owner="{{ remote_user }}"
    group="{{ remote_group }}"
    mode=0600
