#=====  ANSIBLE   =============================================================
#          NAME:  run-installation.yml
#   DESCRIPTION:  Perform software installation
#==============================================================================
---
##
## Create user group/account
##
- name: Create ecuser user group
  group:
    gid=454
    name="{{ ecelerity_group }}"
    state=present
    system=yes

- name: Create ecuser user account
  user:
    createhome=yes
    group="{{ ecelerity_group }}"
    home="{{ ecelerity_home }}"
    name="{{ ecelerity_user }}"
    shell=/bin/bash
    state=present
    system=yes
    uid=454

