#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/common/globalconfig.yml
#   DESCRIPTION:  Configure Zimbra global settings
#==============================================================================
---
##
## global config
##
- name: (POSTINSTALL/COMMON) Apply Zimbra configuration (global config)
  command: "{{ install_dir }}/bin/zmprov mcf +zimbraAccountExtraObjectClass synacorEmailAccount +zimbraAccountExtraObjectClass synacorPortalAccount
    +zimbraCosExtraObjectClass synacorEmailCOS +zimbraDomainExtraObjectClass synacorEmailDomain +zimbraDomainExtraObjectClass synacorPortalDomain
    zimbraHttpDebugHandlerEnabled FALSE zimbraImapCleartextLoginEnabled TRUE zimbraPop3CleartextLoginEnabled TRUE zimbraLmtpNumThreads 250
    zimbraHttpNumThreads 500 zimbraImapNumThreads 600 zimbraPop3NumThreads 600 zimbraImapMaxRequestSize 10240 zimbraImapMaxConnections 600
    zimbraRedoLogDeleteOnRollover TRUE zimbraVersionCheckInterval 0 zimbraVersionCheckSendNotifications FALSE
    zimbraReverseProxySSLCiphers '{{ include_ciphers }}'"
  become: yes
  become_user: zimbra
  become_method: sudo
  when: apply_global_config|bool

- name: (POSTINSTALL/COMMON) Update exclude cipher list (global config)
  command: "{{ install_dir }}/bin/zmprov mcf +zimbraSSLExcludeCipherSuites {{ item }}"
  with_items: "{{ exclude_ciphers|default([]) }}"
  become: yes
  become_user: zimbra
  become_method: sudo
  when: apply_global_config|bool
