#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/maildrop/maildrop-serverconfig.yml
#   DESCRIPTION:  Configure Zimbra server options
#==============================================================================
---
##
## server config
##
- name: (POSTINSTALL) Apply Zimbra configuration (server config)
  command: "{{ install_dir }}/bin/zmprov ms {{ hostvars['{{ inventory_hostname }}'] }} \"zimbraLmtpNumThreads 20 zimbraHttpNumThreads 250 zimbraImapNumThreads 600 zimbraPop3NumThreads 600
    -zimbraLmtpNumThreads 20 -zimbraHttpNumThreads 250 -zimbraImapNumThreads 600 -zimbraPop3NumThreads 600 -zimbraImapMaxRequestSize 200 -zimbraImapMaxConnections 600
    -zimbraHttpDebugHandlerEnabled FALSE -zimbraHttpDebugHandlerEnabled TRUE -zimbraRedoLogDeleteOnRollover FALSE -zimbraRedoLogDeleteOnRollover TRUE\""
  become: yes
  become_user: zimbra
  become_method: sudo
