#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/pop/proxy.yml
#   DESCRIPTION:  Configure Zimbra for a reverse proxy
#==============================================================================
---
##
## Generate dhkey
##
- name: (POSTINSTALL/POP) Generate 2048 bit DH key for zimbra (logjam)
  command: "/usr/bin/openssl dhparam -out {{ zimbra_dhparam_output }} {{ dhparam_keysize }}"
  args:
    creates: "{{ zimbra_dhparam_output }}"
