#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/ldap/multimaster.yml
#   DESCRIPTION:  Enable LDAP multi-master configuration
#==============================================================================
---
##
## Set up multi-master replication
##
- name: (POSTINSTALL) Promote node to master
  command: "{{ install_dir }}/libexec/zmldappromote-replica-mmr -s {{ ldap_rid }}"
  when: not is_master_ldap

- name: (POSTINSTALL) Enable multi-master LDAP replication (zmldapenable-mmr)
  command: "{{ install_dir }}/libexec/zmldapenable-mmr -s {{ ldap_rid }} -m \"ldap://{{ hostvars[inventory_hostname]['ansible_fqdn'] }}:389/\""

- name: (POSTINSTALL) Enable multi-master LDAP replication (local config)
  command: "{{ install_dir }}/bin/zmlocalconfig -e ldap_master_url=\"{{ ldap_master_url }}\" ldap_url=\"{{ ldap_url }}\""

- command: /bin/true
  notify:
    - restart ldap
