#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/ldap/replica.yml
#   DESCRIPTION:  Enable LDAP replicas
#==============================================================================
---
##
## Set up replica if this is an ldap master
##
- name: (POSTINSTALL) Run zmldapenablereplica if this is an LDAP master
  command: /opt/zimbra/libexec/zmldapenablereplica
  become: yes
  become_user: zimbra
  become_method: sudo
  when: is_master_ldap|bool

- command: "{{ install_dir }}/bin/ldap restart"
  become: yes
  become_user: zimbra
  become_method: sudo
  when: is_master_ldap|bool
