#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/ldap/replica.yml
#   DESCRIPTION:  Enable LDAP replicas
#==============================================================================
---
##
## Set up replica if this is an ldap master
##
- name: (POSTINSTALL) Run zmldapenablereplica if this is an LDAP master
  command: /opt/zimbra/libexec/zmldapenablereplica

- command: /bin/true
  notify:
    - restart ldap
