#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/ldap/replica.yml
#   DESCRIPTION:  Enable LDAP replicas
#==============================================================================
---
##
## Set up replica if this is an ldap master
##
- name: (POSTINSTALL/LDAP) Run zmldapenablereplica if this is an LDAP master
  command: /opt/zimbra/libexec/zmldapenablereplica
  become: yes
  become_user: zimbra
  become_method: sudo

- name: (POSTINSTALL/LDAP) Restart LDAP after enabling MMR
  command: "{{ install_dir }}/bin/ldap restart"
  become: yes
  become_user: zimbra
  become_method: sudo
