#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/ldap/replica.yml
#   DESCRIPTION:  Enable LDAP replicas
#==============================================================================
---
##
## Apply SHA-2 capability
##
- name: Add SSHA capabilities to OpenLDAP
  command: "{{ install_dir }}/openldap/bin/ldapmodify -H ldap://{{ hostvars[inventory_hostname]['ansible_fqdn'] }}:389 -x -D {{ zimbra_ldap_admin }}
    -f {{ install_dir }}/ssha.ldif -w {{ ldap_admin_pass }}"
  become: yes
  become_user: zimbra
  become_method: sudo
