#=====  ANSIBLE   =============================================================
#          NAME:  vars/maildrop.yml
#   DEcommandION:  Variables that apply to Zimbra maildrop installations
#==============================================================================
---
- name: (POSTINSTALL) Configure server stores (fstore)
  command: "mkdir {{ install_dir }}/fstore"

- name: (POSTINSTALL) Modify store permissions (fstore)
  command: "chown {{ file_owner }}:{{ group_owner }} {{ install_dir }}/fstore"

- name: (POSTINSTALL) Notify Zimbra of store (primary)
  command: "{{ install_dir }}/bin/zmvolume --add --name fstore --type primaryMessage --compress false --path {{ install_dir }}/fstore"
  become: yes
  become_user: zimbra
  become_method: sudo

- name: (POSTINSTALL) Notify Zimbra of store (primary)
  command: "{{ install_dir }}/bin/zmvolume --id 3 --setCurrent"
  become: yes
  become_user: zimbra
  become_method: sudo

- name: (POSTINSTALL) Notify Zimbra of store (secondary)
  command: "{{ install_dir }}/bin/zmvolume --edit --id 1 --type secondaryMessage --compress true"
  become: yes
  become_user: zimbra
  become_method: sudo

- name: (POSTINSTALL) Notify Zimbra of store (secondary)
  command: "{{ install_dir }}/bin/zmvolume --setCurrent --id 1"
  become: yes
  become_user: zimbra
  become_method: sudo
