#=====  ANSIBLE   =============================================================
#          NAME:  group_vars/ecelerity
#   DESCRIPTION:  Variables that apply to Zimbra maildrop installations
#==============================================================================
---
##
## disks
##
mountpoints:
  - name: /opt
