#=====  ANSIBLE   =============================================================
#          NAME:  group_vars/install-config.yml
#   DESCRIPTION:  Variables that apply to Zimbra maildrop installations
#==============================================================================
---
##
## template updates
##
install_dir: /opt/msys/ecelerity
manager_hostname: "ecmgr01.{{ client_name }}.{{ datacenter }}.synacor.com"
manager_ipaddr: "1.2.3.4"
cluster_group: ec_cluster
control_group: ec_console
maildrops:
  - md01.email.dev.opal.synacor.com
  - md02.email.dev.opal.synacor.com

