#=====  ANSIBLE   =============================================================
#          NAME:  group_vars/ecmgr
#   DESCRIPTION:  Variables that apply to Ecelerity Cluster managers
#==============================================================================
---
##
## disks
##
mountpoints:
  - name: /opt

##
## template updates
##
install_dir: /opt/msys/ecelerity
manager_hostname: "ecmgr01.{{ client_name }}.{{ datacenter }}.synacor.com"
manager_ipaddr: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
cluster_group: ec_cluster
control_group: ec_console

maildrops:
 - list
 - of
 - drops

##
## subversion!
##
inbound.svn.host: "https://ecmgr01.{{ client_name }}.{{ datacenter }}.synacor.com:2027/config/inbound/boot"
outbound.svn.host: "https://ecmgr01.{{ client_name }}.{{ datacenter }}.synacor.com:2027/config/outbound/boot"

##
## datasource config
##
datasources:
  - name: ldap_bind_auth
    uri: "ldap://{{ ldap_host }}:389/????"
    cache-size: 300000
    cache-life: 900
  - name: ldap_auth
    uri: "ldap://{{ ldap_host }}:389/????bindname=uid=zimbra%2ccn=admins%2ccn=zimbra,x-bindpw={{ ldap_admin_pass }}"
    cache-size: 300000
    cache-life: 360
  - name: user_check
    uri: "ldap://{{ ldap_host }}:389/????bindname=uid=zimbra%2ccn=admins%2ccn=zimbra,x-bindpw={{ ldap_admin_pass }}"
    cache-size: 300000
    cache-life: 360
  - name: domain_check
    uri: "ldap://{{ ldap_host }}:389/????bindname=uid=zimbra%2ccn=admins%2ccn=zimbra,x-bindpw={{ ldap_admin_pass }}"
    cache-size: 300000
    cache-life: 360
  - name: md_check
    uri: "ldap://{{ ldap_host }}:389/????bindname=uid=zimbra%2ccn=admins%2ccn=zimbra,x-bindpw={{ ldap_admin_pass }}"
    cache-size: 300000
    cache-life: 360
  - name: catch_all_check
    uri: "ldap://{{ ldap_host }}:389/????bindname=uid=zimbra%2ccn=admins%2ccn=zimbra,x-bindpw={{ ldap_admin_pass }}"
    cache-size: 300000
    cache-life: 360
  - name: bind_check
    uri: "ldap://{{ ldap_host }}:389/????bindname=uid=zimbra%2ccn=admins%2ccn=zimbra,x-bindpw={{ ldap_admin_pass }}"
    cache-size: 300000
    cache-life: 360
  - name: cidr
    uri: "sqlite:{{ install_dir }}/etc/conf/global/ec_lists.db"
    cache-size: 100000
    cache-life: 1800
  - name: global
    uri: "sqlite:{{ install_dir }}/etc/conf/global/ec_lists.db"
    cache-size: 100000
    cache-life: 1800
  - name: internal
    uri: "sqlite:{{ install_dir }}/etc/conf/global/ec_lists.db"
    cache-size: 100000
    cache-life: 1800
  - name: conn
    uri: "sqlite:{{ install_dir }}/etc/conf/global/ec_lists.db"
    cache-size: 100000
    cache-life: 1800
  - name: wlbl
    uri: "sqlite:{{ install_dir }}/etc/conf/global/synacor.db"
    cache-size: 10000
    cache-life: 360
  - name: rate_limit
    uri: "sqlite:{{ install_dir }}/etc/conf/global/synacor.db"
    cache-size: 100000
    cache-life: 60
  - name: fail_check
    uri: "sqlite:{{ install_dir }}/etc/conf/global/synacor.db"
    cache-size: 100000
    cache-life: 60
  - name: relays
    uri: "sqlite:{{ install_dir }}/etc/conf/global/synacor.db"
    cache-size: 10000
    cache-life: 60
  - name: biz
    uri: "sqlite:{{ install_dir }}/etc/conf/global/synacor.db"
    cache-size: 10000
    cache-life: 60
  - name: outbind
    uri: "sqlite:{{ install_dir }}/etc/conf/global/synacor.db"
    cache-size: 10
    cache-life: 60
