#=====  ANSIBLE   =============================================================
#          NAME:  group_vars/ecmgr
#   DESCRIPTION:  Variables that apply to Ecelerity Cluster managers
#==============================================================================
---

