#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/add-client-data.yml
#   DESCRIPTION:  Add client domains to target host
#==============================================================================
---
##
## Add the configured domains...
##
- name: (POSTINSTALL) Add client domains
  command: "{{ install_dir }}/bin/zmprov cd {{ item.name }} zimbraAuthMech zimbra"
  with_items: client_domains
  become: yes
  become_user: zimbra
  become_method: sudo

##
## ...and then set hostnames
##
- name: (POSTINSTALL) Add client domains
  command: "{{ install_dir }}/bin/zmprov md {{ item.name }} zimbraPublicServiceHostname {{ item.public_host_name }}"
  with_items: client_domains
  become: yes
  become_user: zimbra
  become_method: sudo
