#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/maildrop/createaccounts.yml
#   DESCRIPTION:  Create Synacor monitoring accounts
#==============================================================================
---
## create monitoring accounts
- name: (POSTINSTALL) Create accounts
  command: "{{ install_dir }}/bin/zmprov ca {{ item.name }}@{{ domain }} {{ item.password }} {{ default_account_settings }}"
  become: yes
  become_user: zimbra
  become_method: sudo
  with_items: "{{ create_accounts|default([]) }}"
  when: create_default_accounts|bool
