#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/maildrop/webapp.yml
#   DESCRIPTION:  Configure the Zimbra web application
#==============================================================================
---
## update webapps
- name: (POSTINSTALL) Configure Zimbra web application
  command: "/usr/local/bin/replacer.pl --indir {{ install_dir }}/jetty/webapps/zimbra/WEB-INF/classes/messages/ --outdir {{ install_dir }}/jetty/webapps/zimbra/WEB-INF/classes/messages/"

- name: (POSTINSTALL) Configure Zimbra web application
  command: "/usr/local/bin/replacer.pl --indir {{ install_dir }}/jetty/webapps/zimbra/WEB-INF/classes/keys/ --outdir {{ install_dir }}/jetty/webapps/zimbra/WEB-INF/classes/keys/"

- name: (POSTINSTALL) Update Zimbra webapp (zimbrastore.jar)
  command: "cp {{ install_dir }}/jetty/webapps/zimbra/WEB-INF/lib/zimbrastore.jar {{ install_dir }}/jetty/common/lib/"

- name: (POSTINSTALL) Update Zimbra webapp (zimbrastore.jar/ownership)
  command: "chown {{ user_name }}:{{ group_owner}} {{ install_dir }}/jetty/common/lib/zimbrastore.jar"

- name: (POSTINSTALL) Update Zimbra webapp (zimbrastore.jar/permissions)
  command: "chmod 644 {{ install_dir }}/jetty/common/lib/zimbrastore.jar"

- name: (POSTINSTALL) Check if zimbrasoap.jar exists
  stat:
    path="{{ install_dir }}/jetty/webapps/zimbra/WEB-INF/lib/zimbrasoap.jar"
    get_md5=no
  register: zimbrasoap

- name: (POSTINSTALL) Update Zimbra webapp (zimbrasoap.jar)
  command: "cp {{ install_dir }}/jetty/webapps/zimbra/WEB-INF/lib/zimbrasoap.jar {{ install_dir }}/jetty/common/lib/"
  when: zimbrasoap.stat.exists

- name: (POSTINSTALL) Update Zimbra webapp (zimbrastore.jar/ownership)
  command: "chown {{ user_name }}:{{ group_owner}} {{ install_dir }}/jetty/common/lib/zimbrastore.jar"
  when: zimbrasoap.stat.exists

- name: (POSTINSTALL) Update Zimbra webapp (zimbrasoap.jar/permissions)
  command: "chmod 644 {{ install_dir }}/jetty/common/lib/zimbrasoap.jar"
  when: zimbrasoap.stat.exists

- name: (POSTINSTALL) Check if zimbraclient.jar exists
  stat:
    path="{{ install_dir }}/jetty/webapps/zimbra/WEB-INF/lib/zimbraclient.jar"
    get_md5=no
  register: zimbraclient

- name: (POSTINSTALL) Update Zimbra webapp (zimbrasoap.jar)
  command: "cp {{ install_dir }}/jetty/webapps/zimbra/WEB-INF/lib/zimbraclient.jar {{ install_dir }}/jetty/common/lib/"
  when: zimbraclient.stat.exists

- name: (POSTINSTALL) Update Zimbra webapp (zimbraclient.jar/ownership)
  command: "chown {{ user_name }}:{{ group_owner}} {{ install_dir }}/jetty/common/lib/zimbraclient.jar"
  when: zimbraclient.stat.exists

- name: (POSTINSTALL) Update Zimbra webapp (zimbrasoap.jar/permissions)
  command: "chmod 644 {{ install_dir }}/jetty/common/lib/zimbraclient.jar"
  when: zimbraclient.stat.exists
