#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/maildrop/zimlets.yml
#   DESCRIPTION:  Install and configure Zimbra zimlets
#==============================================================================
---
##
## install zimlets
##
- name: (POSTINSTALL) Install zimlets
  yum:
    disable_gpg_check=yes
    name="{{ item.name }}-{{ item.version }}"
    state=present
  with_items: "{{ zimlets|default([]) }}"
  when: install_synacor_skins_zimlets|bool

##
## install skins
##
- name: (POSTINSTALL) Install skins
  yum:
    disable_gpg_check=yes
    name="{{ item.name }}-{{ item.version }}"
    state=present
  with_items: "{{ skins|default([]) }}"
  when: install_synacor_skins_zimlets|bool

##
## custom skins/zimlets
##
- name: (POSTINSTALL) Install zimlets (client specific)
  yum:
    disable_gpg_check=yes
    name="{{ item.name }}-{{ item.version }}"
    state=present
  with_items: "{{ custom_zimlets|default([]) }}"
  when: install_synacor_skins_zimlets|bool

- name: (POSTINSTALL) Install skins (client specific)
  yum:
    disable_gpg_check=yes
    name="{{ item.name }}-{{ item.version }}"
    state=present
  with_items: "{{ custom_skins|default([]) }}"
  when: install_synacor_skins_zimlets|bool

#sudo -u 'zmzimletctl ldapDeploy com_synacor_carbyn'
#sudo -u 'zmzimletctl enable com_synacor_carbyn'
#sudo -u '[ -f /opt/zimbra/zimlets-deployed/com_synacor_carbyn/config_template.xml ] && zmzimletctl configure /opt/zimbra/zimlets-deployed/com_synacor_carbyn/config_template.xml'
#sudo -u 'zmzimletctl ldapDeploy com_synacor_alias'
#sudo -u 'zmzimletctl enable com_synacor_alias'
#sudo -u '[ -f /opt/zimbra/zimlets-deployed/com_synacor_alias/config_template.xml ] && zmzimletctl configure /opt/zimbra/zimlets-deployed/com_synacor_alias/config_template.xml'

##
## set preferred skin
##
- name: (POSTINSTALL) Configure Zimbra zimlets
  command: "{{ install_dir }}/bin/zmprov mc default zimbraPrefSkin {{ zimbra_pref_skin }}"
  become: yes
  become_user: zimbra
  become_method: sudo

##
## remove zimbra pre-installed skins
##
- name: (POSTINSTALL) Configure Zimbra zimlets (global config)
  command: "{{ install_dir }}/bin/zmprov mcf -zimbraInstalledSkin bones -zimbraInstalledSkin hotrod -zimbraInstalledSkin lake -zimbraInstalledSkin lavender -zimbraInstalledSkin lemongrass
    -zimbraInstalledSkin oasis -zimbraInstalledSkin pebble -zimbraInstalledSkin sand -zimbraInstalledSkin sky -zimbraInstalledSkin smoke -zimbraInstalledSkin steel -zimbraInstalledSkin tree
    -zimbraInstalledSkin twilight -zimbraInstalledSkin waves -zimbraInstalledSkin beach -zimbraInstalledSkin bare"
  become: yes
  become_user: zimbra
  become_method: sudo

##
## cleanup after removal
##
- name: (POSTINSTALL) Remove unused skins/themes
  file:
    path="{{ install_dir }}/{{ item }}"
    state=absent
  with_items: "{{ clean_skins|default([]) }}"    
