#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/maildrop/zimlets.yml
#   DESCRIPTION:  Install and configure Zimbra zimlets
#==============================================================================
---
##
## install zimlets
##
- name: (POSTINSTALL) Install zimlets
  yum:
    disable_gpg_check=yes
    name="{{ item.name }}-{{ item.version }}"
    state=present
  with_items: zimlets

##
## custom skins/zimlets
##
- name: (POSTINSTALL) Install zimlets (client specific)
  yum:
    disable_gpg_check=yes
    name="{{ item.name }}-{{ item.version }}"
    state=present
  with_items: custom_zimlets
  when: custom_zimlets is defined

##
## zimlet configuration
##
- name: (POSTINSTALL) Configure zimlet (standard)
  shell: "{{ install_dir }}/bin/zmzimletctl ldapDeploy {{ item.configure_zimlet }}"
  with_items: zimlets

- name: (POSTINSTALL) Configure zimlets (custom)
  shell: "{{ install_dir }}/bin/zmzimletctl ldapDeploy {{ item.configure_zimlet }}"
  with_items: custom_zimlets
  when: custom_zimlets is defined

- name: (POSTINSTALL) Enable zimlets (standard)
  shell: "{{ install_dir }}/bin/zmzimletctl enable {{ item.configure_zimlet }}"
  with_items: zimlets

- name: (POSTINSTALL) Enable zimlets (custom)
  shell: "{{ install_dir }}/bin/zmzimletctl enable {{ item.configure_zimlet }}"
  with_items: zimlets

##
## send install script
##
- name: (POSTINSTALL) Create zimlet installation script
  template:
    src=installZimlets.j2
    dest="/var/tmp/installZimlets.sh"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0755

- name: (POSTINSTALL) Configure zimlet via template (standard)
  shell: "/var/tmp/installZimlets.sh {{ item.configure_zimlet }}"
  with_together:
    - "{{ zimlets }}"
    - "{{ custom_zimlets }}"
