#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/maildrop/zimlets.yml
#   DESCRIPTION:  Install and configure Zimbra zimlets
#==============================================================================
---
##
## install zimlets
##
- name: (POSTINSTALL/MAILDROP) Install zimlets
  yum:
    name="{{ item.name }}-{{ item.version }}"
    state=present
  with_items: zimlets

##
## custom skins/zimlets
##
- name: (POSTINSTALL/MAILDROP) Install zimlets (client specific)
  yum:
    name="{{ item.name }}-{{ item.version }}"
    state=present
  with_items: custom_zimlets
  when: custom_zimlets is defined

##
## zimlet configuration
##
- name: (POSTINSTALL/MAILDROP) Configure zimlet (standard)
  shell: "{{ install_dir }}/bin/zmzimletctl ldapDeploy {{ item.configure_zimlet }}"
  with_items: zimlets

- name: (POSTINSTALL/MAILDROP) Configure zimlets (custom)
  shell: "{{ install_dir }}/bin/zmzimletctl ldapDeploy {{ item.configure_zimlet }}"
  with_items: custom_zimlets
  when: custom_zimlets is defined

- name: (POSTINSTALL/MAILDROP) Enable zimlets (standard)
  shell: "{{ install_dir }}/bin/zmzimletctl enable {{ item.configure_zimlet }}"
  with_items: zimlets

- name: (POSTINSTALL/MAILDROP) Enable zimlets (custom)
  shell: "{{ install_dir }}/bin/zmzimletctl enable {{ item.configure_zimlet }}"
  with_items: custom_zimlets
  when: custom_zimlets is defined

- name: (POSTINSTALL/MAILDROP) Configure zimlet via template (standard)
  shell: "/var/tmp/installZimlets.sh {{ item.configure_zimlet }}"
  with_items: zimlets

- name: (POSTINSTALL/MAILDROP) Configure zimlet via template (custom)
  shell: "/var/tmp/installZimlets.sh {{ item.configure_zimlet }}"
  with_items: custom_zimlets
  when: custom_zimlets is defined
