#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/maildrop/zimlets.yml
#   DESCRIPTION:  Install and configure Zimbra zimlets
#==============================================================================
---
##
## install zimlets
##
- name: (POSTINSTALL) Install zimlets
  yum:
    disable_gpg_check=yes
    name="{{ item }}"
    state=present
  with_items: "{{ zimlets|default([]) }}"
  when: install_synacor_skins_zimlets|bool

##
## install skins
##
- name: (POSTINSTALL) Install skins
  yum:
    disable_gpg_check=yes
    name="{{ item }}"
    state=present
  with_items: "{{ skins|default([]) }}"
  when: install_synacor_skins_zimlets|bool

##
## custom skins/zimlets
##
- name: (POSTINSTALL) Install zimlets (client specific)
  yum:
    disable_gpg_check=yes
    name="{{ item }}"
    state=present
  with_items: "{{ custom_zimlets|default([]) }}"
  when: install_synacor_skins_zimlets|bool

- name: (POSTINSTALL) Install skins (client specific)
  yum:
    disable_gpg_check=yes
    name="{{ item }}"
    state=present
  with_items: "{{ custom_skins|default([]) }}"
  when: install_synacor_skins_zimlets|bool

##
## set preferred skin
##
- name: (POSTINSTALL) Configure Zimbra zimlets
  command: "{{ install_dir }}/bin/zmprov mc default zimbraPrefSkin {{ zimbra_pref_skin }}"
  become: yes
  become_user: zimbra
  become_method: sudo

##
## remove zimbra pre-installed skins
##
- name: (POSTINSTALL) Configure Zimbra zimlets (global config)
  command: "{{ install_dir }}/bin/zmprov mcf -zimbraInstalledSkin bones -zimbraInstalledSkin hotrod -zimbraInstalledSkin lake -zimbraInstalledSkin lavender -zimbraInstalledSkin lemongrass
    -zimbraInstalledSkin oasis -zimbraInstalledSkin pebble -zimbraInstalledSkin sand -zimbraInstalledSkin sky -zimbraInstalledSkin smoke -zimbraInstalledSkin steel -zimbraInstalledSkin tree
    -zimbraInstalledSkin twilight -zimbraInstalledSkin waves -zimbraInstalledSkin beach -zimbraInstalledSkin bare"
  become: yes
  become_user: zimbra
  become_method: sudo

##
## cleanup after removal
##
- name: (POSTINSTALL) Remove unused data
  command: "rm -rf {{ application_home }}/zimlets/com_zimbra_linkedin.zip {{ install_dir }}/zimlets/com_zimbra_dnd.zip
    {{ install_dir }}/zimlets/com_zimbra_social.zip {{ install_dir }}/zimlets/com_zimbra_webex.zip
    {{ install_dir }}/jetty/webapps/zimbra/skins/bare/ {{ install_dir }}/jetty/webapps/zimbra/skins/beach/ {{ install_dir }}/jetty/webapps/zimbra/skins/waves/
    {{ install_dir }}/jetty/webapps/zimbra/skins/twilight/ {{ install_dir }}/jetty/webapps/zimbra/skins/sand/ {{ install_dir }}/jetty/webapps/zimbra/skins/tree/
    {{ install_dir }}/jetty/webapps/zimbra/skins/oasis/ {{ install_dir }}/jetty/webapps/zimbra/skins/lemongrass/ {{ install_dir }}/jetty/webapps/zimbra/skins/lake/
    {{ install_dir }}/jetty/webapps/zimbra/skins/steel/ {{ install_dir }}/jetty/webapps/zimbra/skins/hotrod/ {{ install_dir }}/jetty/webapps/zimbra/skins/smoke/
    {{ install_dir }}/jetty/webapps/zimbra/skins/pebble/ {{ install_dir }}/jetty/webapps/zimbra/skins/bones/ {{ install_dir }}/jetty/webapps/zimbra/skins/sky/
    {{ install_dir }}/jetty/webapps/zimbra/skins/lavender/"
