#=====  ANSIBLE   =============================================================
#          NAME:  build-ecelerity/tasks/apply-configuration.yml
#   DESCRIPTION:  Perform post-installation configuration
#==============================================================================
---
- name: Synchronize configuration
  unarchive:
    src=default.tar.gz
    dest="/opt/msys/ecelerity/etc/conf"
    copy=yes

- name: (POST-INSTALL) Create eccluster.conf
  template:
    src=eccluster.j2
    dest="/opt/msys/ecelerity/etc/conf/global"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

- name: (POST-INSTALL) Create ecelerity-cluster.conf
  template:
    src=ecelerity-cluster.j2
    dest="/opt/msys/ecelerity/etc/conf/global"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

- name: (POST-INSTALL) Create ecelerity.conf
  template:
    src=ecelerity.j2
    dest="/opt/msys/ecelerity/etc/conf/global"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

- name: (POST-INSTALL) Create client_vars.siv
  template:
    src=client_vars.j2
    dest="/opt/msys/ecelerity/etc/conf/default/siv"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0600

- name: (POST-INSTALL) Create auth.lua
  template:
    src=auth.j2
    dest="/opt/msys/ecelerity/etc/conf/default/lua"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644
