#=====  ANSIBLE   =============================================================
#          NAME:  build-ecelerity/tasks/fix-installation.yml
#   DESCRIPTION:  Perform post-installation configuration
#==============================================================================
---
- name: Check if /opt/ecelerity exists
  stat:
    path=/opt/ecelerity
    get_md5=no
  register: exists

- name: If /opt/ecelerity exists, move its content to /opt/msys/ecelerity
  command: mv /opt/ecelerity/bin/* /opt/msys/ecelerity/bin
  when: exists

- name: Remove /opt/ecelerity
  file:
    path=/opt/ecelerity
    state=absent
  when: exists

- name: Create symlink /opt/ecelerity => /opt/msys/ecelerity
  file:
    group="{{ group_name }}"
    owner="{{ user_name }}"
    path=/opt/ecelerity
    src=/opt/msys/ecelerity
    state=link

- name: Change permissions on /opt/msys
  file:
    group="{{ group_name }}"
    owner="{{ user_name }}"
    path=/opt/msys
    recurse=yes
    state=directory

- name: Change permissions on /var/log/ecelerity
  file:
    group="{{ group_name }}"
    owner="{{ user_name }}"
    path=/var/log/ecelerity
    recurse=yes
    state=directory
