#=====  ANSIBLE   =============================================================
#          NAME:  build-ecelerity/tasks/main.yml
#   DESCRIPTION:  Primary entry point for play
#==============================================================================
---
- name: Run ecelerity installation steps (ecmgr)
  include: run-installation.yml
  vars_files:
    - ecmgr.yml
  notify:
    - sync-puppet
    - restart-service
  when: is_ecmgr

- name: Run ecelerity installation steps (MTA)
  vars_files:
    - mta.yml
  include: run-postinstall.yml
  notify:
    - sync-puppet
    - restart-service
  when: is_mta

- name: Remove installer options file
  file:
    path="{{ tmpdir }}/installer.conf"
    state=absent

- name: Remove install archive
  file:
    path="{{ tmpdir }}/ecelerity.tar.gz"
    state=absent

- name: Remove post-install checkout
  file:
    path="{{ tmpdir }}/ecelerity"
    state=absent
