#=====  ANSIBLE   =============================================================
#          NAME:  build-ecelerity/tasks/main.yml
#   DESCRIPTION:  Primary entry point for play
#==============================================================================
---
- name: Run ecelerity installation steps
  include: run-installation.yml
  notify:
    - sync puppet
  meta:
    - flush_handlers

- name: Run ecelerity post-installation steps
  include: run-postinstall.yml
  notify:
    - reload sysctl
    - sync puppet
    - restart service
  meta:
    - flush_handlers

- name: Remove installer options file
  file:
    path="{{ tmpdir }}/installer.conf"

- name: Remove installer options file (ecmgr)
  file:
    path="{{ tmpdir }}/ecelerity"
    state=absent

- name: Remove install archive
  file:
    path="{{ tmpdir }}/ecelerity.tar.gz"
    state=absent

- name: Remove post-install checkout
  file:
    path="{{ tmpdir }}/ecelerity"
    state=absent
