#=====  ANSIBLE   =============================================================
#          NAME:  build-ecelerity/tasks/run-install.yml
#   DESCRIPTION:  Perform software installation
#==============================================================================
---
- name: (INSTALL) Synchronize ecelerity installer
  unarchive:
    src=ecelerity.tar.gz
    dest="{{ tmpdir }}"
    copy=yes

- name: (INSTALL) Create script file for unattended installation
  template:
    src=installer.j2
    dest="{{ tmpdir }}/installer.conf"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

- name: (INSTALL) Process installation
  command: "/usr/bin/env perl {{ tmpdir }}/ecelerity/installer --option-file {{ tmpdir }}/installer.conf --start-services y"
  args:
    chdir: "{{ tmpdir }}/ecelerity"
  become: yes
  become_user: root
  become_method: sudo

