#=====  ANSIBLE   =============================================================
#          NAME:  build-ecelerity/tasks/run-postinstall.yml
#   DESCRIPTION:  Perform post-installation configuration
#==============================================================================
---
- name: (POSTINSTALL) Check for /opt/ecelerity
  stat:
    path=/opt/ecelerity
    get_md5=no
  register: dir_exists

- name: (POSTINSTALL) Copy all files/directories under /opt/ecelerity to /opt/msys/ecelerity
  synchronize:
    dest=/opt/msys/ecelerity/
    recursive=yes
    src=/opt/ecelerity
    rsync_opts="-qcarpt"
  delegate_to: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
  when: dir_exists.stat.exists and dir_exists.stat.isdir

- name: (POSTINSTALL) Remove /opt/ecelerity
  file:
    path=/opt/ecelerity
    state=absent
  when: dir_exists.stat.exists and dir_exists.stat.isdir

- name: (POSTINSTALL) Create symlink /opt/ecelerity => /opt/msys/ecelerity
  file:
    group="{{ group_name }}"
    owner="{{ user_name }}"
    path=/opt/ecelerity
    src="{{ install_dir }}"
    state=link

- name: (POSTINSTALL) Change permissions on /opt/msys
  file:
    group="{{ group_name }}"
    owner="{{ user_name }}"
    path=/opt/msys
    recurse=yes
    state=directory

- name: (POSTINSTALL) Change permissions on /var/log/ecelerity
  file:
    group="{{ group_name }}"
    owner="{{ user_name }}"
    path=/var/log/ecelerity
    recurse=yes
    state=directory

##
## SVN checkout
##
- name: (POSTINSTALL) Check out current configuration
  subversion:
    dest="{{ install_dir }}/etc/conf/"
    executable="{{ svn_path }}"
    force=yes
    password="{{ svn_passwd }}"
    repo="{{ svn_host }}"
    revision=HEAD
    username=admin

- name: (POSTINSTALL) Remove files placed in global
  file:
    path="{{ install_dir }}/etc/conf/default/{{ item }}"
    state=absent
  with_items:
    - webui-common.conf
    - mobile.conf
    - messagescope_remediation.conf
    - messagescope.conf
    - ecelerity-cluster.conf
    - eccluster.conf
    - ecelerity.conf

##
## Copy updated global configuration (global)
##
- name: (POSTINSTALL) Apply configuration files (global)
  copy:
    backup=no
    dest="{{ install_dir }}/etc/conf/"
    group="{{ group_name }}"
    owner="{{ user_name }}"
    src=global

##
## copy default configuration (MTA)
##
- name: (POSTINSTALL) Apply configuration files (default)
  copy:
    backup=no
    dest="{{ install_dir }}/etc/conf/"
    group="{{ group_name }}"
    owner="{{ user_name }}"
    src=default
  when: not is_ecmgr|bool

##
## Create lua directory if it doesn't exit
##
- name: (POSTINSTALL) Create home for lua scripts
  file:
    group="{{ group_name }}"
    owner="{{ user_name }}"
    dest="{{ install_dir }}/etc/conf/default/lua"
    state=directory

##
## Copy customizations to config
##
- name: (POSTINSTALL) Create auth.lua
  template:
    src=auth.j2
    dest="{{ install_dir }}/etc/conf/default/lua/auth.lua"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644
  when: not is_ecmgr|bool

##
## Create siv directory if it doesn't exit
##
- name: (POSTINSTALL) Create home for sieve scripts
  file:
    group="{{ group_name }}"
    owner="{{ user_name }}"
    dest="{{ install_dir }}/etc/conf/default/siv"
    state=directory

- name: (POSTINSTALL) Create client_vars.siv
  template:
    src=client_vars.j2
    dest="{{ install_dir }}/etc/conf/default/siv/client_vars.siv"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644
  when: not is_ecmgr|bool

- name: (POSTINSTALL) Create eccluster.conf
  template:
    src=eccluster.j2
    dest="{{ install_dir }}/etc/conf/global/eccluster.conf"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

- name: (POSTINSTALL) Create ecelerity-cluster.conf
  template:
    src=ecelerity-cluster.j2
    dest="{{ install_dir }}/etc/conf/global/ecelerity-cluster.conf"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

- name: (POSTINSTALL) Create ecelerity.conf
  template:
    src=ecelerity.j2
    dest="{{ install_dir }}/etc/conf/global/ecelerity.conf"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

- name: (POSTINSTALL) Create msgc_server.conf
  template:
    src=msgc_server.j2
    dest="{{ install_dir }}/etc/conf/global/msgc_server.conf"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

##
## Check in all changes
##
- name: (POSTINSTALL) Check in current configuration from cluster manager (MTA)
  shell: "cd {{ install_dir }}/etc/conf; /opt/msys/3rdParty/bin/svn commit --message 'Initial Commit/build via {uid}/Ansible' --no-auth-cache
    --non-interactive --username admin --password {{ svn_passwd }} --recursive"

##
## update sysctl
##
- name: (POSTINSTALL) Create /etc/sysctl.d
  file:
    group=root
    owner=root
    path=/etc/sysctl.d
    state=directory

- name: (POSTINSTALL) Copy sysctl configuration
  copy:
    src="10-ecelerity.conf"
    dest="/etc/sysctl.d/10-ecelerity.conf"
    owner="root"
    group="root"
    mode=0644
