#=====  ANSIBLE   =============================================================
#          NAME:  build-ecelerity/tasks/run-postinstall.yml
#   DESCRIPTION:  Perform post-installation configuration
#==============================================================================
---
- name: Fix installation permissions/directories
  include: fix-installation.yml

- name: Synchronize puppet
  command: /usr/sbin/puppet agent -t

- name: Include ecelerity configuration steps
  include: apply-configuration.yml
  notify:
    - sync-puppet
    - restart-service
    - ecelerity-build-complete
