#=====  ANSIBLE   =============================================================
#          NAME:  build-ecelerity/tasks/run-postinstall.yml
#   DESCRIPTION:  Perform post-installation configuration
#==============================================================================
---

##
## Copy updated global configuration
##
- name: (POSTINSTALL) Apply configuration files (global)
  synchronize:
    delete=yes
    dest="{{ install_dir }}/etc/conf/"
    recursive=yes
    rsync_timeout=0
    rsync_opts="-avr --delete --no-motd --stats --progress"
    src=global

##
## copy default (domain-specific) configuration
##
- name: (POSTINSTALL) Apply configuration files (default)
  synchronize:
    delete=yes
    dest="{{ install_dir }}/etc/conf/"
    recursive=yes
    rsync_timeout=0
    rsync_opts="-avr --delete --no-motd --stats --progress"
    src=default

##
## Copy customizations to config
##
- name: (POSTINSTALL) Create eccluster.conf
  template:
    src=eccluster.j2
    dest="/opt/msys/ecelerity/etc/conf/global"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

- name: (POSTINSTALL) Create ecelerity-cluster.conf
  template:
    src=ecelerity-cluster.j2
    dest="/opt/msys/ecelerity/etc/conf/global"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

- name: (POSTINSTALL) Create ecelerity.conf
  template:
    src=ecelerity.j2
    dest="/opt/msys/ecelerity/etc/conf/global"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

- name: (POSTINSTALL) Create client_vars.siv
  template:
    src=client_vars.j2
    dest="/opt/msys/ecelerity/etc/conf/default/siv"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0600

- name: (POSTINSTALL) Create auth.lua
  template:
    src=auth.j2
    dest="/opt/msys/ecelerity/etc/conf/default/lua"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

##
## update sysctl
##
- name: (POSTINSTALL) Copy sysctl configuration
  copy:
    src="10-ecelerity.conf"
    dest="/etc/sysctl.d/10-ecelerity.conf"
    owner="root"
    group="root"
    mode=0644
  notify:
    - reload sysctl
    - sync puppet
    - restart service
    - notify complete

