#=====  ANSIBLE   =============================================================
#          NAME:  build-ecelerity/tasks/run-install.yml
#   DESCRIPTION:  Perform software installation
#==============================================================================
---
- name: Synchronize ecelerity installer
  unarchive:
    src=ecelerity.tar.gz
    dest="{{ tmpdir }}"
    copy=yes

- name: Create script file for unattended installation
  template:
    src=installer.j2
    dest="{{ tmpdir }}/installer.conf"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

- name: Process installation
  command: "{{ tmpdir }}/ecelerity/installer --option-file {{ tmpdir }}/installer.conf"

