#=====  ANSIBLE   =============================================================
#          NAME:  build-ecelerity/tasks/run-postinstall.yml
#   DESCRIPTION:  Perform post-installation configuration
#==============================================================================
---
- name: Check if /opt/ecelerity exists
  stat:
    path=/opt/ecelerity
    get_md5=no
  register: dir_exists

- name: If /opt/ecelerity exists, move its content to /opt/msys/ecelerity
  command: mv /opt/ecelerity/bin/* /opt/msys/ecelerity/bin
  when: dir_exists.stat.exists

- name: Remove /opt/ecelerity
  file:
    path=/opt/ecelerity
    state=absent
  when: dir_exists.stat.exists

- name: Create symlink /opt/ecelerity => /opt/msys/ecelerity
  file:
    group="{{ group_name }}"
    owner="{{ user_name }}"
    path=/opt/ecelerity
    src="{{ install_dir }}"
    state=link

- name: Change permissions on /opt/msys
  file:
    group="{{ group_name }}"
    owner="{{ user_name }}"
    path=/opt/msys
    recurse=yes
    state=directory

- name: Change permissions on /var/log/ecelerity
  file:
    group="{{ group_name }}"
    owner="{{ user_name }}"
    path=/var/log/ecelerity
    recurse=yes
    state=directory

##
## SVN checkout
##
- name: (POSTINSTALL) Check out current configuration from cluster manager (MTA)
  subversion:
    dest="{{ install_dir }}/conf/"
    password="{{ svn_password }}"
    repo="{{ svn.host }}"
    revision=HEAD
    username=admin
  when: is_mta|bool

##
## Copy updated global configuration (global)
##
- name: (POSTINSTALL) Apply configuration files (global)
  synchronize:
    delete=yes
    dest="{{ install_dir }}/etc/conf/"
    recursive=yes
    rsync_timeout=0
    rsync_opts="-avr --delete --no-motd --stats --progress"
    src=global

##
## copy default configuration (MTA)
##
- name: (POSTINSTALL) Apply configuration files (default)
  synchronize:
    delete=yes
    dest="{{ install_dir }}/etc/conf/"
    recursive=yes
    rsync_timeout=0
    rsync_opts="-avr --delete --no-motd --stats --progress"
    src=default
  when: is_mta|bool

##
## Copy customizations to config
##
- name: (POSTINSTALL) Create eccluster.conf
  template:
    src=eccluster.j2
    dest="{{ install_dir }}/etc/conf/global"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

- name: (POSTINSTALL) Create ecelerity-cluster.conf
  template:
    src=ecelerity-cluster.j2
    dest="{{ install_dir }}/etc/conf/global"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

- name: (POSTINSTALL) Create ecelerity.conf (Cluster Manager)
  template:
    src=ecelerity.j2
    dest="{{ install_dir }}/etc/conf/default"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644
  when: is_ecmgr|bool

- name: (POSTINSTALL) Create ecelerity.conf (MTA)
  template:
    src=ecelerity.j2
    dest="{{ install_dir }}/etc/conf/default"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644
  when: is_mta|bool

- name: (POSTINSTALL) Create client_vars.siv
  template:
    src=client_vars.j2
    dest="{{ install_dir }}/etc/conf/default/siv"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0600
  when: is_mta|bool

- name: (POSTINSTALL) Create auth.lua
  template:
    src=auth.j2
    dest="{{ install_dir }}/etc/conf/default/lua"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644
  when: is_mta|bool

##
## update sysctl
##
- name: (POSTINSTALL) Copy sysctl configuration
  copy:
    src="10-ecelerity.conf"
    dest="/etc/sysctl.d/10-ecelerity.conf"
    owner="root"
    group="root"
    mode=0644
  notify:
    - reload sysctl
    - sync puppet
    - restart service
    - notify complete

