#=====  ANSIBLE   =============================================================
#          NAME:  run-install.yml
#   DESCRIPTION:  Perform software installation
#==============================================================================
---
- name: Synchronize ecelerity installer
  unarchive:
    src=ecelerity.tar.gz
    dest="{{ tmpdir }}"
    copy=yes

- name: Create script file for unattended installation (ecmgr)
  template:
    src=ecmgr.j2
    dest="{{ tmpdir }}/ecmgr"
    owner="{{ file_owner }}"
    group="{{ group_owner }}"
    mode=0644
  when: is_ecmgr

- name: Create script file for unattended installation (mta)
  template:
    src=mta.j2
    dest="{{ tmpdir }}/ecelerity/mta"
    owner="{{ file_owner }}"
    group="{{ group_owner }}"
    mode=0644
  when: is_smtp or is_mx

- name: Process installation
  command: "{{ tmpdir }}/ecelerity/installer --option-file {{ tmpdir }}/ecelerity/ecmgr"
  when: is_ecmgr

- name: Process installation
  command: "{{ tmpdir }}/ecelerity/installer --option-file {{ tmpdir }}/ecelerity/mta"
  when: is_smtp or is_mx
