#=====  ANSIBLE   =============================================================
#          NAME:  build-ecelerity/tasks/run-postinstall.yml
#   DESCRIPTION:  Perform post-installation configuration
#==============================================================================
---
- name: Create symlink /opt/ecelerity => /opt/msys/ecelerity
  file:
    group="{{ group_name }}"
    owner="{{ user_name }}"
    path=/opt/ecelerity
    src="{{ install_dir }}"
    state=link

- name: Change permissions on /opt/msys
  file:
    group="{{ group_name }}"
    owner="{{ user_name }}"
    path=/opt/msys
    recurse=yes
    state=directory

- name: Change permissions on /var/log/ecelerity
  file:
    group="{{ group_name }}"
    owner="{{ user_name }}"
    path=/var/log/ecelerity
    recurse=yes
    state=directory

- name: Remove files placed in global
  file:
    path="{{ install_dir }}/etc/conf/default/{{ item }}"
    state=absent
  with_items:
    - webui-common.conf
    - mobile.conf
    - messagescope_remediation.conf
    - messagescope.conf
    - ecelerity-cluster.conf
    - eccluster.conf
    - ecelerity.conf

##
## SVN checkout
##
- name: (POSTINSTALL) Check out current configuration
  subversion:
    dest="{{ install_dir }}/conf/"
    password="{{ svn_password }}"
    repo="{{ svn.host }}"
    revision=HEAD
    username=admin

##
## Copy updated global configuration (global)
##
- name: (POSTINSTALL) Apply configuration files (global)
  copy:
    backup=no
    dest="{{ install_dir }}/etc/conf/"
    group="{{ group_name }}"
    owner="{{ user_name }}"
    src=global

##
## copy default configuration (MTA)
##
- name: (POSTINSTALL) Apply configuration files (default)
  synchronize:
    delete=yes
    dest="{{ install_dir }}/etc/conf/"
    recursive=yes
    rsync_timeout=0
    rsync_opts="-avr --delete --no-motd --stats --progress"
    src=default
  when: not is_ecmgr|bool

##
## Copy customizations to config
##
- name: (POSTINSTALL) Create auth.lua
  template:
    src=auth.j2
    dest="{{ install_dir }}/etc/conf/default/lua/auth.lua"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644
  when: not is_ecmgr|bool

- name: (POSTINSTALL) Create client_vars.siv
  template:
    src=client_vars.j2
    dest="{{ install_dir }}/etc/conf/default/siv/client_vars.siv"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644
  when: not is_ecmgr|bool

- name: (POSTINSTALL) Create eccluster.conf
  template:
    src=eccluster.j2
    dest="{{ install_dir }}/etc/conf/global/eccluster.conf"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

- name: (POSTINSTALL) Create ecelerity-cluster.conf
  template:
    src=ecelerity-cluster.j2
    dest="{{ install_dir }}/etc/conf/global/ecelerity-cluster.conf"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

- name: (POSTINSTALL) Create ecelerity.conf
  template:
    src=ecelerity.j2
    dest="{{ install_dir }}/etc/conf/global/ecelerity.conf"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

- name: (POSTINSTALL) Create msgc_server.conf
  template:
    src=msgc_server.j2
    dest="{{ install_dir }}/etc/conf/global/msgc_server.conf"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

##
## Check in all changes
##
- name: (POSTINSTALL) Check in current configuration from cluster manager (MTA)
  shell: "cd {{ install_dir }}/etc/conf; /opt/msys/3rdparty/bin/svn commit --message 'Initial Commit, build via {uid}/Ansible' --no-auth-cache
    --non-interactive --username admin --password {{ svn_password }} --recursive"

##
## update sysctl
##
- name: (POSTINSTALL) Create /etc/sysctl.d
  file:
    group=root
    owner=root
    path=/etc/sysctl.d
    state=directory

- name: (POSTINSTALL) Copy sysctl configuration
  copy:
    src="10-ecelerity.conf"
    dest="/etc/sysctl.d/10-ecelerity.conf"
    owner="root"
    group="root"
    mode=0644
