#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/create-disks.yml
#   DESCRIPTION:  Entry point for the Zimbra build play
#==============================================================================
---
- name: Creating physical volumes
  command: pvcreate /dev/sdb /dev/sdc /dev/sdd

- name: Creating Zimbra volume group
  command: vgcreate vg_zimbra /dev/sdb /dev/sdc /dev/sdd

- name: Creating logical volumes
  command: /sbin/lvcreate -l 12799 -n lv_zimbra vg_zimbra /dev/sdb
  command: /sbin/lvcreate -l 76799 -n lv_index vg_zimbra /dev/sdc
  command: /sbin/lvcreate -l 25599 -n lv_db vg_zimbra /dev/sdd

- name: Creating filesystem on vg_zimbra/lv_zimbra
  filesystem:
    fstype=ext4
    dev=/dev/vg_zimbra/lv_zimbra

- name: Creating filesystem on vg_zimbra/lv_db
  filesystem:
    fstype=ext4
    dev=/dev/vg_zimbra/lv_db

- name: Creating filesystem on vg_zimbra/lv_index
  filesystem:
    fstype=ext4
    dev=/dev/vg_zimbra/lv_index

- name: Mounting filesystem /opt/zimbra
  mount:
    fstype=ext4
    name=/opt/zimbra
    src=/dev/vg_zimbra/lv_zimbra
    state=mounted

- name: Mounting filesystem /opt/zimbra/db
  mount:
    fstype=ext4
    name=/opt/zimbra/db
    src=/dev/vg_zimbra/lv_db
    state=mounted

- name: Mounting filesystem /opt/zimbra/index
  mount:
    fstype=ext4
    name=/opt/zimbra/index
    src=/dev/vg_zimbra/lv_index
    state=mounted
