#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/main.yml
#   DESCRIPTION:  Entry point for the Zimbra build play
#==============================================================================
---
- name: (MAIN) Run pre-installation steps
  include: run-preinstall.yml

- name: (MAIN) Run Zimbra installation steps
  include: run-installation.yml
  notify:
    - sync puppet
    - restart service

- meta: flush_handlers

- name: (MAIN) Run Zimbra post-installation
  include: run-postinstall.yml
  notify:
    - sync puppet
    - restart service
