#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/main.yml
#   DESCRIPTION:  Entry point for the Zimbra build play
#==============================================================================
---
- name: (MAIN) Check if mount points exist
  stat:
    path="{{ item.name }}"
    get_md5=FALSE
    get_checksum=FALSE
  with_items: "{{ mountpoints }}"

- name: (MAIN) Run Zimbra installation steps
  include: run-installation.yml

- name: (MAIN) Run Zimbra post-installation
  include: run-postinstall.yml
