#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/patch-zmsetup.yml
#   DESCRIPTION:  Copies and applies appropriate patch file for zmsetup
#==============================================================================
---
- name: (POSTINSTALL) Create resource file for unattended installation
  template:
    src=unattended.j2
    dest="{{ install_dir }}/conf/unattended.conf"
    owner="{{ file_owner }}"
    group="{{ group_owner }}"
    mode=0644

- name: (POSTINSTALL) Copy zmsetup patch (8.0.6_GA_5922.RHEL6_64-20131203103753)
  copy:
    src="806.patch"
    dest="{{ tmpdir }}/zmsetup.patch"
    owner="{{ file_owner }}"
    group="{{ group_owner }}"
    mode=0644
  when: "'{{ pkg_version }}' == '8.0.6_GA_5922.RHEL6_64-20131203103753'"

- name: (POSTINSTALL) Copy zmsetup patch (all others)
  copy:
    src="all.patch"
    dest="{{ tmpdir }}/zmsetup.patch"
    owner="{{ file_owner }}"
    group="{{ group_owner }}"
    mode=0644
  when: "'{{ pkg_version }}' != '8.0.6_GA_5922.RHEL6_64-20131203103753'"

- name: (POSTINSTALL) Patch zmsetup
  shell: "patch {{ install_dir }}/libexec/zmsetup.pl < {{ tmpdir }}/zmsetup.patch"
  ignore_errors: yes

- name: (POSTINSTALL) Run zmsetup
  command: "{{ install_dir }}/libexec/zmsetup.pl -d -c {{ install_dir }}/conf/unattended.conf"
