#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/run-postinstall.yml
#   DESCRIPTION:  Configure Zimbra maildrop post-installation
#==============================================================================
---
##
## FIRST THINGS FIRST. Correct perms on /opt/zimbra
##
- name: (POSTINSTALL) Correct permissions on /opt/zimbra
  file:
    path=/opt/zimbra
    group=zimbra
    owner=zimbra
    recurse=yes
    state=directory

##
## Update OpenSSL and java.security
##
- name: (POSTINSTALL) Remove existing OpenSSL installation
  file:
    path="{{ install_dir }}/openssl-1.0.1f"
    state=absent

- name: (POSTINSTALL) Synchronize OpenSSL update
  unarchive:
    copy=yes
    dest="{{ install_dir }}"
    group="{{ group_name }}"
    owner="{{ user_name }}"
    src="{{ playbook_dir }}/files/openssl-1.0.1f.tgz"

- name: (POSTINSTALL) Update java.security DNS cache timeout
  replace:
    backup=yes
    dest="{{ install_dir }}/java/jre/lib/security/java.security"
    group="{{ group_name }}"
    mode=0644
    owner="{{ user_name }}"
    regexp='^#networkaddress.cache.ttl=-1$'
    replace='networkaddress.cache.ttl=600'

##
## Run zmsetup after installation to configure
##
- name: (POSTINSTALL) Create resource file for unattended installation
  template:
    src=unattended.j2
    dest="{{ install_dir }}/conf/unattended.conf"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

- name: (POSTINSTALL) Copy zmsetup patch (8.0.6_GA_5922.RHEL6_64-20131203103753)
  copy:
    src=806.patch
    dest="{{ tmpdir }}/zmsetup.patch"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644
  when: "'{{ pkg_version }}' == '8.0.6_GA_5922.RHEL6_64-20131203103753'"

- name: (POSTINSTALL) Copy zmsetup patch (all others)
  copy:
    src=all.patch
    dest="{{ tmpdir }}/zmsetup.patch"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644
  when: "'{{ pkg_version }}' != '8.0.6_GA_5922.RHEL6_64-20131203103753'"

- name: (POSTINSTALL) Patch zmsetup
  shell: "patch {{ install_dir }}/libexec/zmsetup.pl < {{ tmpdir }}/zmsetup.patch"
  ignore_errors: yes

##
## Shut down services before continuing
##
- name: (POSTINSTALL) Stop services before running zmsetup
  service:
    name=zimbra
    state=stopped
  ignore_errors: yes

- name: (POSTINSTALL) Kill any remaining slapd pids
  command: pkill slapd
  ignore_errors: yes
  when: is_ldap|bool

- name: (POSTINSTALL) Kill any remaining Zimbra pids
  command: pkill java
  ignore_errors: yes

- name: (POSTINSTALL) Kill any remaining Zimbra sessions
  command: killall -u zimbra
  ignore_errors: yes
  notify:
    - sync puppet

- meta: flush_handlers

##
## Run zmsetup to apply configuration
##
##
- name: (POSTINSTALL) Run zmsetup
  command: "{{ install_dir }}/libexec/zmsetup.pl -d -c {{ install_dir }}/conf/unattended.conf"
  notify:
    - sync puppet

- meta: flush_handlers

##
## fix permissions on install
##
- name: (POSTINSTALL) Fix Zimbra permissions
  file:
    group="{{ group_name }}"
    owner="{{ user_name }}"
    path="{{ install_dir }}"
    recurse=yes
    state=directory
  notify:
    - sync puppet

- meta: flush_handlers

##
## Common configuration for all zimbra installations
##
- name: (POSTINSTALL) Include Zimbra local configuration tasks
  include: common/localconfig.yml

##
## global zimbra configuration (applies to all nodes)
##
- name: (POSTINSTALL) Include Zimbra global configuration tasks
  include: common/globalconfig.yml

##
## server zimbra configuration (applies to THIS node)
##
- name: (POSTINSTALL) Include Zimbra server configuration tasks
  include: common/serverconfig.yml

##
## enforce ssl authentication
##
- name: (POSTINSTALL) Enable mixed-mode
  include: common/ssl-redirect.yml
  when: enforce_ssl|bool

##
## disable zimbra backups
##
- name: (POSTINSTALL) Turn off Zimbra backups
  command: "{{ install_dir }}/bin/zmschedulebackup -F"
  become: yes
  become_user: zimbra
  become_method: sudo

#
# Apply licensing
#
- name: (POSTINSTALL) Apply licensing
  command: "{{ install_dir }}/bin/zmlicense -a"
  become: yes
  become_user: zimbra
  become_method: sudo
  when: activate_license|bool

##
## POP-specific config
##
##
## Copy templates to server to apply dhparam for zimbra's nginx
##
- name: (POSTINSTALL/POP) Copy zimbra nginx configuration files to targets
  template:
    src="{{ item.src }}"
    dest="{{ item.dest }}"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644
  with_items:
    - { src: nginx.conf.web.https.default.j2, dest: "{{ install_dir }}/conf/nginx/templates/nginx.conf.web.https.default.template" }
    - { src: nginx.conf.web.https.j2, dest: "{{ install_dir }}/conf/nginx/templates/nginx.conf.web.https.template" }

- name: (POSTINSTALL) Include reverse proxy configuration tasks
  include: pop/proxy.yml
  when: is_pop|bool and use_reverse_proxy|bool

- name: (POSTINSTALL) Apply logjam fix
  include: pop/logjam.yml
  when: is_pop|bool

#
# Maildrop-specific config
#
- name: (POSTINSTALL) Include Zimbra CoS tasks
  include: maildrop/cos.yml
  when: is_maildrop|bool and apply_cos|bool and not is_pop|bool

- name: (POSTINSTALL) Add client data
  include: maildrop/add-client-data.yml
  when: is_maildrop|bool and apply_domains|bool and not is_pop|bool

- name: (POSTINSTALL) Include maildrop store configuration tasks
  include: maildrop/storeconfig.yml
  when: is_maildrop|bool and setup_stores|bool and not is_pop|bool

- name: (POSTINSTALL) Include monitoring account creation
  include: maildrop/createaccounts.yml
  when: is_maildrop|bool and create_default_accounts|bool and not is_pop|bool

- name: (POSTINSTALL) Include Zimbra webapp modifications
  include: maildrop/webapp.yml
  when: is_maildrop|bool and not is_pop|bool

- name: (POSTINSTALL) Include Zimbra maildrop whitelists
  include: maildrop/whitelist.yml
  when: is_maildrop|bool or is_pop|bool

##
## send install script
##
- name: (POSTINSTALL) Create zimlet installation script
  template:
    src=installZimlets.j2
    dest="/var/tmp/installZimlets.sh"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0755
  when: is_maildrop|bool and install_synacor_skins_zimlets|bool

- name: (POSTINSTALL) Include Zimbra zimlet installations
  include: maildrop/zimlets.yml
  when: is_maildrop|bool and install_synacor_skins_zimlets|bool

- name: (POSTINSTALL) Include Zimbra skins installations
  include: maildrop/skins.yml
  when: is_maildrop|bool and install_synacor_skins_zimlets|bool

- name: (POSTINSTALL) Include Scality installation/configuration tasks
  include: maildrop/scality.yml
  when: is_maildrop|bool and use_scality|bool

##
## LDAP specific config
##
- name: (POSTINSTALL/LDAP) Copy SSHA LDIF to target
  copy:
    src=ssha.ldif
    dest="{{ install_dir }}/ssha.ldif"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644
  when: is_ldap|bool

- name: (POSTINSTALL) Enable SSHA-2 (LDAP)
  include: ldap/ssha.yml
  when: is_ldap|bool

- name: (POSTINSTALL) Disable stats (LDAP)
  include: ldap/disable-stats.yml
  when: is_ldap|bool

- name: (POSTINSTALL) Include LDAP replication tasks
  include: ldap/replica.yml
  when: is_ldap|bool and is_master_ldap|bool

- name: (POSTINSTALL) Include LDAP multi-master tasks
  include: ldap/multimaster.yml
  when: is_ldap|bool and is_multimaster|bool

##
## Shut down services before continuing
##
- name: (POSTINSTALL) Stop services
  service:
    name=zimbra
    state=stopped

- name: (POSTINSTALL) Kill any remaining slapd pids
  command: pkill slapd
  ignore_errors: yes
  when: is_ldap|bool

- name: (POSTINSTALL) Kill any remaining Zimbra pids
  command: pkill java
  ignore_errors: yes

- name: (POSTINSTALL) Kill any remaining Zimbra sessions
  command: killall -u zimbra
  ignore_errors: yes

##
## Clear the Jetty work directory
##
- name: (POSTINSTALL) Clear the Jetty work directory
  file:
    path="{{ install_dir }}/jetty/work"
    state=absent

##
## Re-create the Jetty work directory
##
- name: (POSTINSTALL) Rebuild the Jetty work directory
  file:
    group="{{ group_name }}"
    mode=0755
    owner="{{ user_name }}"
    path="{{ install_dir }}/jetty/work"
    state=directory

##
## Re-compile all JSPs
##
- name: (POSTINSTALL) JSP recompilation
  command: "{{ install_dir }}/libexec/zmjsprecompile"
  become: yes
  become_user: zimbra
  become_method: sudo
  when: is_maildrop|bool and zimbra_major_version == 8

##
## Fix permissions as necessary
##
- name: (POSTINSTALL) Set Zimbra permissions
  command: "{{ install_dir }}/libexec/zmfixperms -extended"

- name: (POSTINSTALL) Turn off fsck
  command: "/sbin/tune2fs -c 0 -i 0 {{ install_dir }}"
  when: disable_fsck
  notify:
    - sync puppet

- meta: flush_handlers

##
## Bring up zimbra
##
- name: (POSTINSTALL) Start zimbra on completion
  service:
    name=zimbra
    state=restarted
  when: not is_pop|bool

##
## POSTINSTALL COMPLETE
##
