#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/run-installation.yml
#   DESCRIPTION:  Perform software installation
#==============================================================================
---
##
## Run installation steps
##
- name: (INSTALL) Install selected packages
  yum:
    name: "{{ item.name }}-{{ item.version }}"
    state: present
  with_items: zimbra_packages
  notify:
    - sync puppet

- meta:
    flush_handlers

- name: (INSTALL) Sync with puppet master
  command: puppet agent -t
  ignore_errors: yes

##
## INSTALLATION COMPLETE
##
