#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/run-postinstall.yml
#   DESCRIPTION:  Configure Zimbra maildrop post-installation
#==============================================================================
---
###
### Run zmsetup after installation to configure
###
- name: (POSTINSTALL) Create resource file for unattended installation
  template:
    src=unattended.j2
    dest="{{ install_dir }}/conf/unattended.conf"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

- name: (POSTINSTALL) Copy zmsetup patch (8.0.6_GA_5922.RHEL6_64-20131203103753)
  copy:
    src="806.patch"
    dest="{{ tmpdir }}/zmsetup.patch"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644
  when: "'{{ pkg_version }}' == '8.0.6_GA_5922.RHEL6_64-20131203103753'"

- name: (POSTINSTALL) Copy zmsetup patch (all others)
  copy:
    src="all.patch"
    dest="{{ tmpdir }}/zmsetup.patch"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644
  when: "'{{ pkg_version }}' != '8.0.6_GA_5922.RHEL6_64-20131203103753'"

- name: (POSTINSTALL) Patch zmsetup
  shell: "patch {{ install_dir }}/libexec/zmsetup.pl < {{ tmpdir }}/zmsetup.patch"
  ignore_errors: yes

##
## Shut down services before continuing
##
- name: (POSTINSTALL) Stop LDAP
  command: "{{ install_dir }}/bin/ldap stop"
  become: yes
  become_user: zimbra
  become_method: sudo
  ignore_errors: yes

- name: (POSTINSTALL) Kill any remaining slapd pids
  command: pkill slapd
  ignore_errors: yes

- name: (POSTINSTALL) Stop Zimbra services
  service:
    name=zimbra
    state=stopped

- name: (POSTINSTALL) Kill any remaining Zimbra pids
  command: pkill java
  ignore_errors: yes

- name: (POSTINSTALL) Kill any remaining Zimbra sessions
  command: killall -u zimbra
  ignore_errors: yes

##
## Run zmsetup to apply configuration
##
##
- name: (POSTINSTALL) Run zmsetup
  command: "{{ install_dir }}/libexec/zmsetup.pl -d -c {{ install_dir }}/conf/unattended.conf"

##
## Notify puppet after install
##
- name: Notify puppet
  command: puppet agent -t
  ignore_errors: yes

##
## Shut down services before continuing
##
- name: (POSTINSTALL) Stop LDAP
  command: "{{ install_dir }}/bin/ldap stop"
  become: yes
  become_user: zimbra
  become_method: sudo
  ignore_errors: yes

- name: (POSTINSTALL) Kill any remaining slapd pids
  command: pkill slapd
  ignore_errors: yes

- name: (POSTINSTALL) Stop Zimbra services
  service:
    name=zimbra
    state=stopped

- name: (POSTINSTALL) Kill any remaining Zimbra pids
  command: pkill java
  ignore_errors: yes

- name: (POSTINSTALL) Kill any remaining Zimbra sessions
  command: killall -u zimbra
  ignore_errors: yes

##
## Update OpenSSL and java.security
##
- name: (POSTINSTALL) Remove existing OpenSSL installation
  file:
    path="{{ install_dir }}/openssl-1.0.1f"
    state=absent

- name: (POSTINSTALL) Synchronize OpenSSL update
  unarchive:
    copy=yes
    dest="{{ install_dir }}"
    group="{{ group_name }}"
    owner="{{ user_name }}"
    src="{{ playbook_dir }}/files/openssl-1.0.1f.tgz"

- name: (POSTINSTALL) Copy java.security update to target host
  copy:
    src="{{ playbook_dir }}/files/java.security"
    dest="{{ install_dir }}/java/jre/lib/security/java.security"
    owner="{{ user_name }}"
    group="{{ group_name }}"
    mode=0644

##
## fix permissions on install
##
- name: (POSTINSTALL) Fix Zimbra permissions
  file:
    group="{{ group_name }}"
    owner="{{ user_name }}"
    path="{{ install_dir }}"
    recurse=yes
    state=directory

##
## Common configuration for all zimbra installations
##
- name: (POSTINSTALL) Include Zimbra local configuration tasks
  include: common/localconfig.yml

##
## restart services
##
- name: (POSTINSTALL) Start LDAP
  command: "{{ install_dir }}/bin/ldap start"
  become: yes
  become_user: zimbra
  become_method: sudo
  when: is_ldap

- name: (POSTINSTALL) Start Zimbra
  command: "{{ install_dir }}/bin/zmcontrol start"
  become: yes
  become_user: zimbra
  become_method: sudo

##
## continue applying configuration changes
##
- name: (POSTINSTALL) Include Zimbra global configuration tasks
  include: common/globalconfig.yml

- name: (POSTINSTALL) Include Zimbra server configuration tasks
  include: common/serverconfig.yml

- name: (POSTINSTALL) Enable mixed-mode
  include: common/ssl-redirect.yml

- name: (POSTINSTALL) Turn off Zimbra backups
  command: "{{ install_dir }}/bin/zmschedulebackup -F"
  become: yes
  become_user: zimbra
  become_method: sudo

##
## POP-specific config
##
- name: (POSTINSTALL) Include reverse proxy configuration tasks
  include: pop/proxy.yml
  when: use_reverse_proxy

##
## Maildrop-specific config
##
- name: (POSTINSTALL) Include Zimbra CoS tasks
  include: maildrop/cos.yml
  when: is_maildrop

- name: (POSTINSTALL) Add client data
  include: maildrop/add-client-data.yml
  when: is_maildrop

- name: (POSTINSTALL) Include maildrop store configuration tasks
  include: maildrop/storeconfig.yml
  when: is_maildrop and setup_stores

- name: (POSTINSTALL) Include monitoring account creation
  include: maildrop/createaccounts.yml
  when: is_maildrop and create_maildrop_accounts

- name: (POSTINSTALL) Include Zimbra webapp modifications
  include: maildrop/webapp.yml
  when: is_maildrop

- name: (POSTINSTALL) Include Zimbra zimlet installations
  include: maildrop/zimlets.yml
  when: is_maildrop and install_synacor_skins_zimlets

- name: (POSTINSTALL) Include Scality installation/configuration tasks
  include: maildrop/scality.yml
  when: is_maildrop and use_scality

##
## LDAP specific config
##
- name: (POSTINSTALL) Include LDAP replication tasks
  include: ldap/replica.yml
  when: is_ldap and is_master_ldap

- name: (POSTINSTALL) Disable stats (LDAP)
  include: ldap/disable-stats.yml
  when: is_ldap

- name: (POSTINSTALL) Include LDAP multi-master tasks
  include: ldap/multimaster.yml
  when: is_ldap and is_multimaster

##
## restart services
##
- name: (POSTINSTALL) Stopping Zimbra to apply changes
  command: /usr/local/bin/zimbra_service.sh -k

- name: (POSTINSTALL) Pause for 30 seconds to allow completion
  pause:
    seconds=30

- name: (POSTINSTALL) JSP recompilation
  command: "{{ install_dir }}/libexec/zmjsprecompile"
  when: is_maildrop and zimbra_major_version == 8

- name: (POSTINSTALL) Clear the Zimbra work directory
  command: "{{ install_dir }}/jetty/work/*"
  when: is_maildrop and zimbra_major_version == 8

- name: (POSTINSTALL) Set Zimbra permissions
  command: "{{ install_dir }}/libexec/zmfixperms -extended"

- name: (POSTINSTALL) Apply licensing
  command: "{{ install_dir }}/bin/zmlicense -a"
  become: yes
  become_user: zimbra
  become_method: sudo
  when: activate_license

- name: (POSTINSTALL) Turn off fsck
  command: "/sbin/tune2fs -c 0 -i 0 {{ install_dir }}"
  when: disable_fsck

- name: Notify puppet
  command: puppet agent -t
  ignore_errors: yes

##
## Bring up zimbra
##
- name: (POSTINSTALL) Start zimbra on completion
  service:
    name=zimbra
    state=restarted

##
## POSTINSTALL COMPLETE
##
