#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/run-installation.yml
#   DESCRIPTION:  Perform software installation
#==============================================================================
---
##
## Run installation steps
##
- name: (INSTALL) Install selected packages
  yum:
    name: "{{ item.name }}-{{ item.version }}"
    state: present
  with_items:
    - "{{ base_packages|default([]) }}"
    - "{{ packages|default([]) }}"

- name: Notify puppet
  command: puppet agent -t
  ignore_errors: yes

##
## INSTALLATION COMPLETE
##
