#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/run-install.yml
#   DESCRIPTION:  Performs base Zimbra installation for maildrop/LDAP
#==============================================================================
---
##
## Run installation steps
##
- name: (INSTALL) Install selected packages
  yum:
    name: "{{ item.name }}-{{ item.version }}"
    state: present
  with_items: "{{ packages }}"

- name: Notify puppet
  command: puppet agent -t
  ignore_errors: yes

##
## INSTALLATION COMPLETE
##

