#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/postinstall.yml
#   DESCRIPTION:  Configure Zimbra maildrop post-installation
#==============================================================================
---
## shut down
- name: (POSTINSTALL) Stopping Zimbra to apply changes
  command: /usr/local/bin/zimbra_service.sh -k
  ignore_errors: yes

- name: (POSTINSTALL) Kill any remaining Zimbra processes
  command: killall -u zimbra
  ignore_errors: yes

- name: Pause for 30 seconds to allow completion
  pause:
    seconds=30

- name: (POSTINSTALL) JSP recompilation
  command: "{{ install_dir }}/libexec/zmjsprecompile"
  when: is_maildrop and zimbra_major_version == 8
  become: yes
  become_user: zimbra
  become_method: sudo

- name: (POSTINSTALL) Clear the Zimbra work directory
  command: "{{ install_dir }}/jetty/work/*"
  when: is_maildrop and zimbra_version == 8
  become: yes
  become_user: zimbra
  become_method: sudo

- name: (POSTINSTALL) Set Zimbra permissions
  command: "{{ install_dir }}/libexec/zmfixperms -extended"

- name: (POSTINSTALL) Starting Zimbra to apply changes
  command: /usr/local/bin/zimbra_service.sh -s

- name: (POSTINSTALL) Turn off fsck
  command: "/sbin/tune2fs -c 0 -i 0 {{ install_dir }}"
  when: disable_fsck
