#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/run-install.yml
#   DESCRIPTION:  Performs base Zimbra installation for maildrop/LDAP
#==============================================================================
---
##
## Run installation steps
##
- name: (INSTALL) Install netcat
  yum:
    name=nc
    state=present

- name: (INSTALL) Install zimbra core
  yum:
    name="zimbra-core-{{ pkg_version }}.{{ hostvars[inventory_hostname]['ansible_architecture'] }}"
    state=present

- name: (INSTALL) Include LDAP installation tasks
  include: ldap/install.yml
  when: is_ldap

- name: (INSTALL) Include maildrop installation tasks
  include: maildrop/install.yml
  when: is_maildrop

- name: (INSTALL) Include POP installation tasks
  include: pop/install.yml
  when: is_pop

- name: Notify puppet
  command: /usr/bin/puppet agent -t
  ignore_errors: yes

##
## INSTALLATION COMPLETE
##
