#=====  ANSIBLE   =============================================================
#          NAME:  build-zimbra/tasks/postinstall.yml
#   DESCRIPTION:  Configure Zimbra maildrop post-installation
#==============================================================================
---
##
## Update OpenSSL and java.security
##
- name: (POSTINSTALL) Remove existing OpenSSL installation
  file:
    path="{{ install_dir }}/openssl-1.0.1f"
    state=absent

- name: (POSTINSTALL) Synchronize OpenSSL update
  unarchive:
    copy=yes
    dest="{{ install_dir }}"
    group="{{ group_owner }}"
    owner="{{ file_owner }}"
    src="{{ playbook_dir }}/files/openssl-1.0.1f.tgz"

- name: (POSTINSTALL) Copy java.security update to target host
  copy:
    src="{{ playbook_dir }}/files/java.security"
    dest="{{ install_dir }}/java/jre/lib/security/java.security"
    owner="{{ file_owner }}"
    group="{{ group_owner }}"
    mode=0644

## shut things down, change permissions, restart
- name: (POSTINSTALL) Fix Zimbra permissions
  file:
    group="{{ group_owner }}"
    owner="{{ file_owner }}"
    path="{{ install_dir }}"
    recurse=yes
    state=directory

## if this is an LDAP master turn that shit on
- include: ldap/tasks/replica.yml
  when: is_master_ldap

## if multi-master is enabled, set it up
- include: ldap/tasks/multimaster.yml
  when: is_multimaster

##
## apply LDAP config
##
- include: common/localconfig.yml

##
## Start services so things actually fucking work
##
- name: (POSTINSTALL) Start Zimbra services
  command: /etc/init.d/zimbra start

- name: Pause for 30 seconds to allow completion
  pause:
    prompt="Pause for 30 seconds to allow LDAP shutdown"
    seconds=30

- include: common/globalconfig.yml

- include: common/serverconfig.yml

- include: common/cos.yml

- name: (POSTINSTALL) Turn off Zimbra backups
  command: "{{ install_dir }}/bin/zmschedulebackup -F"
  become: yes
  become_user: zimbra
  become_method: sudo

- name: (POSTINSTALL) Apply licensing
  command: "{{ install_dir }}/bin/zmlicense -a"
  when: activate_license
  become: yes
  become_user: zimbra
  become_method: sudo

- include: pop/tasks/proxy.yml
  when: use_reverse_proxy

- include: maildrop/tasks/storeconfig.yml
  when: is_maildrop and setup_stores

- include: maildrop/tasks/createaccounts.yml
  when: is_maildrop and create_maildrop_accounts

- include: maildrop/tasks/webapp.yml
  when: is_maildrop

- include: maildrop/tasks/zimlets.yml
  when: is_maildrop and install_synacor_skins_zimlets

- include: maildrop/tasks/scality.yml
  when: is_maildrop and use_scality

## shut down
- name: (POSTINSTALL) Stopping Zimbra to apply changes
  command: /usr/local/bin/zimbra_service.sh -k

- name: Pause for 30 seconds to allow completion
  pause:
    prompt="Pause for 30 seconds to allow LDAP shutdown"
    seconds=30

- name: (POSTINSTALL) JSP recompilation
  command: "{{ install_dir }}/libexec/zmjsprecompile"
  when: is_maildrop and zimbra_major_version == 8
  become: yes
  become_user: zimbra
  become_method: sudo

- name: (POSTINSTALL) Clear the Zimbra work directory
  command: "{{ install_dir }}/jetty/work/*"
  when: is_maildrop and zimbra_version == 8
  become: yes
  become_user: zimbra
  become_method: sudo

- name: (POSTINSTALL) Set Zimbra permissions
  command: "{{ install_dir }}/libexec/zmfixperms -extended"

- name: (POSTINSTALL) Starting Zimbra to apply changes
  command: /usr/local/bin/zimbra_service.sh -s

- name: (POSTINSTALL) Turn off fsck
  command: "/sbin/tune2fs -c 0 -i 0 {{ install_dir }}"
  when: disable_fsck
