#=====  ANSIBLE   =============================================================
#          NAME:  group_vars/all
#   DESCRIPTION:  Variables that apply to all plays within this playbook
#==============================================================================
---
##
## ecelerity auth
##
adminpass: 13atbac0n
svcpasswd: 13atbac0n

##
## ldap auth
##
create_admin_pass: 2Dv0WpQ5
ldap_admin_pass: aa2NsoOU
ldap_root_pass: 2cGFQN6G
ldap_rep_pass: Iu3ZLbMw
ldap_post_pass: YSzHPG3Y
ldap_amavis_pass: I6HtzEko
ldap_nginx_password: bWYso2UF
ldap_bes_searcher_password: V5QSaV8d
