#=====  ANSIBLE   =============================================================
#          NAME:  group_vars/nginx.yml
#   DESCRIPTION:  Variables that apply to Zimbra maildrop installations
#==============================================================================
---
##
## install data
##
build_type: POP/IMAP Proxy
nginx_conf: /etc/nginx/nginx.conf
nginx_version: 1.4.7-3
dhparam_keysize: 2048
dhparam_output: /etc/nginx/ssl/dhparams-nginx.pem
install_packages: zimbra-core zimbra-memcached zimbra-proxy
is_ldap: FALSE
is_maildrop: FALSE
is_pop: TRUE
is_mta: FALSE
create_default_accounts: FALSE
create_maildrop_accounts: FALSE
setup_stores: FALSE
use_scality: FALSE
use_reverse_proxy: TRUE
activate_license: FALSE
do_create_domain: no
ldap_url: "ldap://ldap01.{{ client_name }}.{{ datacenter }}.synacor.com:389/"
