#=====  ANSIBLE   =============================================================
#          NAME:  group_vars/nginx.yml
#   DESCRIPTION:  Variables that apply to Zimbra maildrop installations
#==============================================================================
---
##
## install data
##
build_type: POP/IMAP Proxy
nginx_conf: /etc/nginx/nginx.conf
nginx_version: 1.4.7-3
nginx_user: nginx
dhparam_keysize: 2048
dhparam_output: /etc/nginx/ssl/dhparams-nginx.pem
is_ldap: FALSE
is_maildrop: FALSE
is_pop: TRUE
is_mta: FALSE
create_default_accounts: FALSE
create_maildrop_accounts: FALSE
setup_stores: FALSE
use_scality: FALSE
use_reverse_proxy: TRUE
activate_license: FALSE
blacklist_file: /opt/zimbra/conf/nginx/blacklisted_ips.txt
hosts:
  - domain: default.com
    port.pop3: 110
    port.pop3s: 995
    port.imap: 143
    port.imaps: 993

cos_id: b1d6a2cb-d4bb-4479-a613-c45736d7986c
