#=====  ANSIBLE   =============================================================
#          NAME:  group_vars/maildrop.yml
#   DESCRIPTION:  Variables that apply to Zimbra maildrop installations
#==============================================================================
---
clean_skins:
  - zimlets/com_zimbra_linkedin.zip
  - zimlets/com_zimbra_dnd.zip
  - zimlets/com_zimbra_social.zip
  - zimlets/com_zimbra_webex.zip
  - jetty/webapps/zimbra/skins/bare
  - jetty/webapps/zimbra/skins/beach
  - jetty/webapps/zimbra/skins/waves
  - jetty/webapps/zimbra/skins/twilight
  - jetty/webapps/zimbra/skins/sand
  - jetty/webapps/zimbra/skins/tree
  - jetty/webapps/zimbra/skins/oasis
  - jetty/webapps/zimbra/skins/lemongrass
  - jetty/webapps/zimbra/skins/lake
  - jetty/webapps/zimbra/skins/steel
  - jetty/webapps/zimbra/skins/hotrod
  - jetty/webapps/zimbra/skins/smoke
  - jetty/webapps/zimbra/skins/pebble
  - jetty/webapps/zimbra/skins/bones
  - jetty/webapps/zimbra/skins/sky
  - jetty/webapps/zimbra/skins/lavender
