#=====  ANSIBLE   =============================================================
#          NAME:  group_vars/maildrop.yml
#   DESCRIPTION:  Variables that apply to Zimbra maildrop installations
#==============================================================================
---
##
## yum installs
##
packages:
  - name: zimbra-core
    version: "{{ pkg_version }}.{{ hostvars[inventory_hostname]['ansible_architecture'] }}"
  - name: zimbra-store
    version: "{{ pkg_version }}.{{ hostvars[inventory_hostname]['ansible_architecture'] }}"
  - name: zimbra-apache
    version: "{{ pkg_version }}.{{ hostvars[inventory_hostname]['ansible_architecture'] }}"
  - name: zimbra-spell
    version: "{{ pkg_version }}.{{ hostvars[inventory_hostname]['ansible_architecture'] }}"
